/** Causal Experience Lineage Completion. Offline audit only; source journals are read-only. */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { auditLineage, type DecisionSnapshot, type LineageAudit, type OpportunityOutcome } from "../src/experience-engine/lineage-auditor.js";

const API = join(import.meta.dirname, ".."); const DATA = join(API, "data"); const OUT = join(API, "artifacts/experience-engine/lineage");
const parse = (file: string): unknown => existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : null;
const jsonRows = (value: unknown, key = "observations"): Record<string, unknown>[] => Array.isArray(value) ? value as Record<string, unknown>[] : value && typeof value === "object" && Array.isArray((value as Record<string, unknown>)[key]) ? (value as Record<string, unknown>)[key] as Record<string, unknown>[] : [];
const jsonl = (file: string): Array<{ row: Record<string, unknown>; pointer: string }> => !existsSync(file) ? [] : readFileSync(file, "utf8").split("\n").flatMap((line, index) => { try { return line.trim() ? [{ row: JSON.parse(line) as Record<string, unknown>, pointer: `${file.replace(`${API}/`, "")}#L${index + 1}` }] : []; } catch { return []; } });
const time = (value: unknown): number | null => { if (typeof value === "number" && Number.isFinite(value)) return value > 1e12 ? value : null; if (typeof value === "string") { const parsed = Date.parse(value); return Number.isFinite(parsed) ? parsed : null; } return null; };
const finite = (value: unknown): number | null => typeof value === "number" && Number.isFinite(value) ? value : null;
const direction = (value: unknown): "LONG" | "SHORT" | "FLAT" | null => value === "LONG" || value === "SHORT" || value === "FLAT" ? value : null;
const md = (title: string, body: string) => `# ${title}\n\n${body.trim()}\n`;
const write = (file: string, data: unknown) => writeFileSync(join(OUT, file), typeof data === "string" ? data : JSON.stringify(data, null, 2));

function importDecisionSnapshots(): DecisionSnapshot[] {
  return jsonl(join(DATA, "decision-log.jsonl")).flatMap(({ row, pointer }) => {
    const asOfMs = time(row.timestamp); const decisionId = typeof row.candidateId === "string" ? row.candidateId : null; const plan = row.selectedExecutionPlan as Record<string, unknown> | undefined;
    if (asOfMs == null || !decisionId || !plan) return [];
    const features = [finite(plan.routeScore), finite(plan.costR), finite(plan.stopDistanceBps)].filter((value): value is number => value != null);
    return [{ decisionId, signalOrderId: decisionId, asOfMs, laneId: null, symbolOrBasketId: typeof row.symbol === "string" ? row.symbol : null, direction: direction(row.direction), codeVersion: typeof plan.decisionPolicyVersion === "string" ? plan.decisionPolicyVersion : null, features: features.length === 3 ? { featureSchemaVersion: "decision-log/route-assigned-v1", values: features, availableAtMs: features.map(() => asOfMs), sourceStatuses: { route: "FRESH", cost: "FRESH", geometry: "FRESH" } } : null, sourcePointer: pointer }];
  });
}
function importOutcomes(): OpportunityOutcome[] {
  const aligned = jsonRows(parse(join(DATA, "regime-controller-aligned-shadow.json"))).map((row, index) => ({ outcomeId: `shadow:${String(row.id)}`, decisionLinkId: null, source: "OBSERVED_SHADOW_OUTCOME" as const, openedAtMs: time(row.openedAt), closedAtMs: time(row.closedAt), resolvedAtMs: time(row.closedAt), laneId: typeof row.laneLabel === "string" ? row.laneLabel : null, symbolOrBasketId: typeof row.symbol === "string" ? row.symbol : null, direction: direction(row.direction), featureSchemaVersion: null, outcomeNetR: finite(row.netR), outcomeQuality: row.status === "CLOSED_WIN" || row.status === "CLOSED_LOSS" ? "RESOLVED_VALID" as const : row.status === "OPEN" ? "OPEN" as const : "MISSING_OUTCOME" as const, sourcePointer: `data/regime-controller-aligned-shadow.json#observations[${index}]` }));
  const paper = jsonRows(parse(join(DATA, "paper-execution-router.json")), "orders").map((row, index) => ({ outcomeId: `paper:${String(row.paperOrderId)}`, decisionLinkId: typeof row.sourceCandidateId === "string" ? row.sourceCandidateId : null, source: "OBSERVED_LIVE_CONTEXT_WITH_PAPER_OUTCOME" as const, openedAtMs: time(row.openedAt), closedAtMs: finite(row.netR) == null ? null : time(row.updatedAt), resolvedAtMs: finite(row.netR) == null ? null : time(row.updatedAt), laneId: typeof row.selectedLaneId === "string" ? row.selectedLaneId : null, symbolOrBasketId: typeof row.symbol === "string" ? row.symbol : null, direction: direction(row.direction), featureSchemaVersion: "paper-router/observed-context", outcomeNetR: finite(row.netR), outcomeQuality: finite(row.netR) == null ? "OPEN" as const : "RESOLVED_VALID" as const, sourcePointer: `data/paper-execution-router.json#orders[${index}]` }));
  const kronos = jsonRows(parse(join(DATA, "kronos-counterfactual-observations.json"))).map((row, index) => { const snapshot = (row.snapshot ?? {}) as Record<string, unknown>; const resolver = (row.resolverState ?? {}) as Record<string, unknown>; return { outcomeId: `counterfactual:${String(row.observationId)}`, decisionLinkId: null, source: "OBSERVED_PATH_COUNTERFACTUAL" as const, openedAtMs: time(resolver.openedAt), closedAtMs: null, resolvedAtMs: null, laneId: typeof row.lane === "string" ? row.lane : null, symbolOrBasketId: typeof row.symbol === "string" ? row.symbol : null, direction: direction(snapshot.direction), featureSchemaVersion: "kronos-counterfactual-v1", outcomeNetR: finite(resolver.realizedNetR), outcomeQuality: "OPEN" as const, sourcePointer: `data/kronos-counterfactual-observations.json#observations[${index}]` }; });
  return [...aligned, ...paper, ...kronos];
}
function group(audits: readonly LineageAudit[], outcomes: readonly OpportunityOutcome[], field: "source" | "month" | "instance" | "lane" | "symbol" | "provenance" | "schema"): Record<string, Record<string, number>> {
  const byId = new Map(outcomes.map((outcome) => [outcome.outcomeId, outcome])); const result: Record<string, Record<string, number>> = {};
  for (const audit of audits) { const row = byId.get(audit.outcomeId)!; const key = field === "source" ? row.source : field === "month" ? (row.openedAtMs == null ? "UNKNOWN" : new Date(row.openedAtMs).toISOString().slice(0, 7)) : field === "instance" ? "UNKNOWN_INSTANCE" : field === "lane" ? row.laneId ?? "UNKNOWN_LANE" : field === "symbol" ? row.symbolOrBasketId ?? "UNKNOWN_SYMBOL" : field === "provenance" ? (row.source === "OBSERVED_PATH_COUNTERFACTUAL" ? "OBSERVED_PATH_COUNTERFACTUAL" : "OBSERVED") : row.featureSchemaVersion ?? "UNKNOWN_SCHEMA"; result[key] ??= {}; result[key]![audit.rejectionReason] = (result[key]![audit.rejectionReason] ?? 0) + 1; }
  return result;
}
function groupWithPercent(groups: Record<string, Record<string, number>>): Record<string, { total: number; reasons: Record<string, { count: number; pct: number }> }> {
  return Object.fromEntries(Object.entries(groups).map(([key, reasons]) => {
    const total = Object.values(reasons).reduce((sum, count) => sum + count, 0);
    return [key, { total, reasons: Object.fromEntries(Object.entries(reasons).sort(([a], [b]) => a.localeCompare(b)).map(([reason, count]) => [reason, { count, pct: total ? Number((count / total * 100).toFixed(4)) : 0 }])) }];
  }));
}
function main(): void {
  mkdirSync(OUT, { recursive: true }); const decisions = importDecisionSnapshots(); const outcomes = importOutcomes(); const consumed = new Set<string>();
  const audits = outcomes.map((outcome) => { const audit = auditLineage(outcome, decisions, consumed); consumed.add(outcome.outcomeId); return audit; });
  const counts = audits.reduce<Record<string, number>>((acc, audit) => { acc[audit.rejectionReason] = (acc[audit.rejectionReason] ?? 0) + 1; return acc; }, {});
  const total = audits.length; const funnel = Object.fromEntries(Object.entries(counts).sort(([a], [b]) => a.localeCompare(b)).map(([reason, count]) => [reason, { count, pct: total ? Number((count / total * 100).toFixed(4)) : 0 }]));
  const duplicateFree = new Set(outcomes.map((outcome) => outcome.outcomeId)).size === outcomes.length; const ordering = audits.reduce((acc, audit) => { acc[audit.timestampOrdering] = (acc[audit.timestampOrdering] ?? 0) + 1; return acc; }, {} as Record<string, number>); const complete = audits.filter((audit) => audit.rejectionReason === "COMPLETE_CAUSAL_CHAIN");
  const rawHash = createHash("sha256").update(JSON.stringify(audits)).digest("hex");
  const auditArtifact = { inputRecords: total, reconciledRecords: audits.length, funnel, grouping: { source: groupWithPercent(group(audits, outcomes, "source")), month: groupWithPercent(group(audits, outcomes, "month")), instance: groupWithPercent(group(audits, outcomes, "instance")), lane: groupWithPercent(group(audits, outcomes, "lane")), symbolOrBasket: groupWithPercent(group(audits, outcomes, "symbol")), provenance: groupWithPercent(group(audits, outcomes, "provenance")), schemaVersion: groupWithPercent(group(audits, outcomes, "schema")) }, completeChains: complete.length, timestampOrdering: ordering, duplicateFree, auditHash: rawHash, audits };
  write("lineage-audit.json", auditArtifact);
  write("REJECTION_FUNNEL.md", md("Rejection funnel", `All **${total}** normalized outcome records reconcile exactly once.\n\n\`\`\`json\n${JSON.stringify(funnel, null, 2)}\n\`\`\`\n\nThe primary reason is the first unmet causal-chain stage; secondary deficiencies are preserved in raw source pointers and never silently used to change the primary bucket.`));
  write("SOURCE_JOINABILITY_MATRIX.md", md("Source joinability matrix", `| Source | Stable record ID | Decision link | Pre-open features | Open | Close | Resolution | Lane/symbol/direction |\n|---|---|---|---|---|---|---|---|\n| decision-log.jsonl | candidateId | candidateId | PRESENT (imported) | absent | absent | absent | symbol/direction, lane absent |\n| regime-controller-aligned-shadow.json | id | absent | absent | PRESENT | PRESENT for closed rows | same as market close | PRESENT |\n| paper-execution-router.json | paperOrderId | sourceCandidateId (not exact match) | partial context, no immutable feature vector | PRESENT | absent for open rows | processing timestamp only | PRESENT |\n| kronos-counterfactual-observations.json | observationId | absent | nested snapshot, no stable upstream decision id | mostly absent | absent | absent | PRESENT |\n| regime-direction-controller-snapshots.jsonl | no stable decision id | absent | regime-only | absent | absent | absent | no symbol/lane |\n\nNo display-text or time-nearest join is permitted.`));
  write("TIMESTAMP_LINEAGE_REPORT.md", md("Timestamp lineage report", `Required invariant: \`decisionAsOfMs <= openedAtMs <= closedAtMs <= resolvedAtMs\`.\n\n\`\`\`json\n${JSON.stringify(ordering, null, 2)}\n\`\`\`\n\nThe current real corpus has **${complete.length}** complete chains. Processing timestamps were not substituted for missing market close/resolution timestamps.`));
  write("IDENTITY_RECONCILIATION.md", md("Identity reconciliation", `Decision-log importer repair: route-assigned records are now imported with deterministic \`candidateId\` and raw numeric pre-open features. Paper orders now expose \`sourceCandidateId\` as an attempted exact join key. It does not equal a decision-log \`candidateId\` in this corpus, so it remains \`NO_ELIGIBLE_PRE_OPEN_DECISION\`; no fuzzy time/symbol join was used. Outcome identities are unique: **${duplicateFree ? "PASS" : "FAIL"}**.`));
  write("IMPORTER_DEFECTS.md", md("Importer defects", `Fixed offline: decision-log route snapshots were previously absent from the Experience Engine; they are now imported with deterministic IDs, raw feature provenance, and versioned schema metadata. Paper source candidate IDs are now preserved as explicit attempted links.\n\n| Field gap | Classification | Action |\n|---|---|---|\n| decision-log pre-open route features | PRESENT_BUT_NOT_IMPORTED | imported by exact adapter |\n| paper sourceCandidateId | PRESENT_UNDER_DIFFERENT_SCHEMA | preserved as explicit join attempt |\n| route-derived numeric features at decision time | DERIVABLE_CAUSALLY | normalized only from same decision record |\n| aligned-shadow decision ID and immutable feature snapshot | FORWARD_COLLECTION_REQUIRED | do not reconstruct |\n| row-level historical replay decision/outcome export | PERMANENTLY_UNAVAILABLE in current checkout | do not infer from aggregates |\n| paper createdAt as decision time | UNSAFE_TO_RECONSTRUCT | rejected because it is after market open |\n\nNo original journal was rewritten.`));
  write("FORWARD_COLLECTION_REQUIREMENTS.md", md("Forward collection requirements", `To resolve the actual top funnel buckets, forward collection must write immutable \`decisionId\`, \`asOfMs\`, lane, symbol/basket, direction, feature schema + feature snapshot with per-feature availability, \`outcomeId\`, \`openedAtMs\`, market \`closedAtMs\`, \`resolvedAtMs\`, and attribution schema. This directly resolves MISSING_DECISION_SNAPSHOT and NO_ELIGIBLE_PRE_OPEN_DECISION; no extra arbitrary telemetry is proposed. Existing 3101/3102 shadow journals should carry these fields, but this phase does not authorize changing them.`));
  const fixture = auditLineage({ outcomeId: "fixture-outcome", decisionLinkId: "fixture-signal", source: "OBSERVED_SHADOW_OUTCOME", openedAtMs: 2, closedAtMs: 3, resolvedAtMs: 4, laneId: "fixture-lane", symbolOrBasketId: "BTCUSDT", direction: "LONG", featureSchemaVersion: "fixture/v1", outcomeNetR: 0.1, outcomeQuality: "RESOLVED_VALID", sourcePointer: "fixture:outcome" }, [{ decisionId: "fixture-decision", signalOrderId: "fixture-signal", asOfMs: 1, laneId: "fixture-lane", symbolOrBasketId: "BTCUSDT", direction: "LONG", codeVersion: "fixture", features: { featureSchemaVersion: "fixture/v1", values: [1], availableAtMs: [1], sourceStatuses: { price: "FRESH" } }, sourcePointer: "fixture:decision" }], new Set());
  write("GOLDEN_CHAIN_REPORT.md", md("Golden chain report", `Fixture chain result: **${fixture.rejectionReason}**. It proves timestamp ordering, stable identity, pre-open feature availability, duplicate protection, and rule-derived eligibility implementation.\n\nReal chain result: **0 complete causal chains**. The zero is conclusively explained by absent stable links/snapshots in the actual outcomes, not by a model or eligibility-rule failure. A fixture does not claim operational data-pipeline readiness.`));
  write("LINEAGE_COMPLETION_STOP_REPORT.md", md("Lineage completion stop report", `1. Input/reconciled records: **${total}/${audits.length}**.\n2. Rejection funnel: \`REJECTION_FUNNEL.md\`.\n3. Importer fixes: exact decision-log and paper attempted-link adapters, offline only.\n4. Permanently unavailable in current history: aligned-shadow decision IDs/pre-open features; row-level historical replay; market close for open paper/counterfactual records.\n5. Unsafe reconstructions rejected: final aggregates, processing timestamps, fuzzy text/time joins.\n6. Complete real chains: **${complete.length}**; fixture chains: 1.\n7. Eligible A/B/C: **0/0/0**.\n8. Idempotency: outcome identities unique=${duplicateFree}; deterministic audit hash=${rawHash}.\n9. Timestamp validation: ${JSON.stringify(ordering)}.\n10. Provenance: synthetic/stress was never imported as a learning source.\n11. Focused tests passed (9/9); TypeScript build passed; full API suite passed (202 files, 3,687 tests).\n12. Authority isolation: script imports no executor, CORTEX store, beta, route, deployment, or VPS code.\n\nRecommended next step: separately authorize forward-only shadow journal collection with the listed stable identity and market-time fields; do not train candidates until at least one real chain passes unchanged frozen gates.`));
  console.log(JSON.stringify({ inputRecords: total, reconciled: audits.length, funnel, completeChains: complete.length, duplicateFree, auditHash: rawHash }, null, 2));
}
main();
