/**
 * Immutable Daily Range close-chart artifact.
 *
 * This is deliberately an SVG generated by the execution process, not a
 * dashboard screenshot or a fresh public-chart query.  Every candle is capped
 * at the confirmed exchange exit timestamp, so reopening a closed report
 * cannot silently pull in later price action.
 */
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { resolve, sep } from "node:path";

import type { FuturesKline } from "./binance-futures-private.js";

export const DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION = "daily-range-closed-chart-svg-v7" as const;
type DailyRangeClosedChartSnapshotVersion =
  | typeof DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION
  | "daily-range-closed-chart-svg-v6"
  | "daily-range-closed-chart-svg-v5"
  | "daily-range-closed-chart-svg-v4";

export type DailyRangeClosedChartSnapshot = {
  version: DailyRangeClosedChartSnapshotVersion;
  /** CAPTURED assets are immutable. PENDING means the close was safe but the visual feed failed. */
  status: "CAPTURED" | "PENDING" | "UNAVAILABLE";
  requestedAt: string;
  capturedAt: string | null;
  source: "BINANCE_USDM_COMPLETED_CANDLES";
  entryAt: string | null;
  exitAt: string | null;
  assetFile: string | null;
  mimeType: "image/svg+xml" | null;
  fiveMinuteCandleCount: number;
  /** Complete 1m candles rendered after C2; absent on pre-v6 archives. */
  oneMinuteCandleCount?: number;
  fourHourCandleCount: number;
  reason: string | null;
};

type SnapshotDirection = "LONG" | "SHORT";
type SnapshotEntryPolicy = "LEGACY_CONTINUATION" | "CONTINUATION" | "FADE";

export type DailyRangeClosedChartSnapshotTrade = Readonly<{
  tradeId: string;
  symbol: string;
  direction: SnapshotDirection;
  entryPolicy?: SnapshotEntryPolicy;
  breakoutDirection?: "UP" | "DOWN" | null;
  entrySubmittedAt: string;
  entryFilledAt: string | null;
  entryFillPrice: number | null;
  /** Frozen fill-to-stop distance used by the R-trail at the time of entry. */
  initialRiskPrice?: number | null;
  exitTimestamp: string | null;
  exitPrice: number | null;
  rangeHigh: number;
  rangeLow: number;
  stopPrice: number | null;
  takeProfitPrice: number | null;
  rrTarget: number;
  referenceTimezone?: "UTC" | "America/New_York";
  referenceRangeOpenTime?: number | null;
  referenceRangeCloseTime?: number | null;
  confirmationBar1: SnapshotCandle;
  confirmationBar2: SnapshotCandle;
  /** First persisted +0.50R MFE arm for FADE R-trail trades. */
  fadeRTrail?: {
    trailArmedAt?: string | null;
    armThresholdR?: number | null;
  } | null;
}>;

export type SnapshotCandle = Readonly<{
  openTime: number;
  closeTime: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}>;

export type DailyRangeClosedChartSnapshotClient = Pick<
  { getKlines(symbol: string, interval: "1m" | "5m" | "4h", opts?: { startTime?: number; endTime?: number }): Promise<FuturesKline[]> },
  "getKlines"
>;

const FIVE_MINUTE_MS = 5 * 60_000;
const FIVE_MINUTE_EMA_CONTEXT_BARS = 50;
// This is presentation padding only. No candle after the confirmed exit is
// fetched or rendered; it keeps the final event marker away from the edge.
const CLOSE_LABEL_RIGHT_PADDING_BARS = 3;
// Execution points intentionally share one neutral color. The entry/exit
// price levels and their labels retain their own colors for readability.
const EXECUTION_MARKER_POINT_COLOR = "#FFFFFF";

const COLORS = {
  background: "#071016",
  panel: "#0b171e",
  border: "#29414c",
  grid: "#263d48",
  text: "#dbe7ec",
  dim: "#8fa5ae",
  up: "#5ce4a6",
  down: "#ff777d",
  entry: "#f8fafc",
  exit: "#c4b5fd",
  stop: "#ff6b6b",
  takeProfit: "#46d39a",
  rangeHigh: "#6fb3d6",
  rangeLow: "#f0b54b",
  acceptance: "#78c8ff",
  ema20: "#eedd88",
  ema50: "#aa4499",
  resistance: "#ff9f66",
  support: "#77b7ff",
  partial: "#8fa5ae",
} as const;

type OverlayPoint = { openTime: number; value: number };
type StructuralLine = { kind: "RESISTANCE" | "SUPPORT"; points: OverlayPoint[] };
type PriceLevel = { label: string; price: number; color: string; dash?: string };
type SnapshotMarker = {
  label: string;
  at: number;
  price: number;
  color: string;
  pointColor?: string;
  position: "above" | "below" | "middle";
  labelAnchor?: "start" | "end";
  labelPosition?: "above" | "below";
  /** A short, collision-safe identity rendered next to a displaced C1/C2 marker. */
  markerTag?: string;
  markerTagPosition?: "above" | "below";
  /** Visual displacement only; the stem remains anchored at the exact event price/time. */
  visualOffsetY?: number;
  /** C1/C2 are visually attached to the triggering candle, while their rail keeps the exact close timestamp. */
  candleOpenTime?: number;
  eventId?: "C1" | "C2" | "ENTRY" | "ARM" | "EXIT";
};
type SnapshotEvent = { label: string; at: number; price: number; color: string; pointColor?: string };
type RiskZone = { from: number; to: number; color: string; label: string };
type PartialCandleInterval = { start: number; end: number; intervalLabel: "1m" | "5m" };

function finite(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function positive(value: unknown): value is number {
  return finite(value) && value > 0;
}

function toMs(value: string | null | undefined): number | null {
  if (!value) return null;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function asSnapshotCandle(value: FuturesKline | SnapshotCandle): SnapshotCandle | null {
  if (!positive(value.openTime) || !positive(value.closeTime)
    || !positive(value.open) || !positive(value.high) || !positive(value.low) || !positive(value.close)
    || !finite(value.volume) || value.volume < 0) return null;
  return {
    openTime: value.openTime,
    closeTime: value.closeTime,
    open: value.open,
    high: value.high,
    low: value.low,
    close: value.close,
    volume: value.volume,
  };
}

function distinctCompletedCandles(rows: readonly (FuturesKline | SnapshotCandle)[], startMs: number, exitMs: number): SnapshotCandle[] {
  const unique = new Map<number, SnapshotCandle>();
  for (const row of rows) {
    const candle = asSnapshotCandle(row);
    // A partial candle that was still forming when the exit happened must never
    // appear in a "last chart at close" artifact.
    if (!candle || candle.openTime < startMs || candle.closeTime >= exitMs) continue;
    unique.set(candle.openTime, candle);
  }
  return [...unique.values()].sort((left, right) => left.openTime - right.openTime);
}

/**
 * The 5m C2 candle is the decision bar. From its confirmed close onward, a
 * contiguous sequence of fully completed 1m candles gives a much more useful
 * review of the execution path. A gap falls back to the truthful 5m archive;
 * it must never be hidden by mixing an incomplete 1m sequence into the chart.
 */
function mixedExecutionCandles(input: {
  fiveMinuteCandles: readonly SnapshotCandle[];
  oneMinuteCandles: readonly SnapshotCandle[];
  c2CloseAt: number;
  exitAt: number;
}): { candles: SnapshotCandle[]; usesOneMinuteAfterC2: boolean } {
  const { fiveMinuteCandles, oneMinuteCandles, c2CloseAt, exitAt } = input;
  const lastCompleteMinuteOpen = Math.floor((exitAt - 60_000) / 60_000) * 60_000;
  if (lastCompleteMinuteOpen < c2CloseAt) return { candles: [...fiveMinuteCandles], usesOneMinuteAfterC2: false };
  const expectedCount = Math.floor((lastCompleteMinuteOpen - c2CloseAt) / 60_000) + 1;
  const postC2 = oneMinuteCandles
    .filter((candle) => candle.openTime >= c2CloseAt && candle.openTime <= lastCompleteMinuteOpen)
    .sort((left, right) => left.openTime - right.openTime);
  const contiguous = postC2.length === expectedCount
    && postC2.every((candle, index) => candle.openTime === c2CloseAt + index * 60_000 && candle.closeTime < exitAt);
  if (!contiguous) return { candles: [...fiveMinuteCandles], usesOneMinuteAfterC2: false };
  return {
    candles: [
      ...fiveMinuteCandles.filter((candle) => candle.openTime < c2CloseAt),
      ...postC2,
    ].sort((left, right) => left.openTime - right.openTime),
    usesOneMinuteAfterC2: true,
  };
}

function escapeXml(value: string): string {
  return value.replace(/[<>&"']/g, (character) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "\"": "&quot;", "'": "&apos;" })[character]!);
}

function formatPrice(value: number): string {
  const digits = value < 0.0001 ? 10 : value < 0.01 ? 8 : value < 1 ? 6 : value < 100 ? 4 : 2;
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value);
}

function formatOverlayPrice(value: number): string {
  const digits = value < 0.0001 ? 10 : value < 0.01 ? 8 : value < 1 ? 6 : value < 100 ? 4 : 2;
  return new Intl.NumberFormat("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value);
}

function consolidateCoincidentLevels(levels: readonly PriceLevel[]): PriceLevel[] {
  const groups: PriceLevel[][] = [];
  for (const level of levels) {
    const tolerance = Math.max(1e-10, Math.abs(level.price) * 1e-10);
    const group = groups.find((candidate) => Math.abs(candidate[0]!.price - level.price) <= tolerance);
    if (group) group.push(level);
    else groups.push([level]);
  }
  return groups.map((group) => {
    if (group.length === 1) return group[0]!;
    const labels = group.map((level) => level.label);
    const preferred = group.find((level) => level.label === "Actual exit fill") ?? group[0]!;
    const fourHourBoundary = labels.find((value) => value === "4H breakout" || value === "4H breakdown");
    const label = labels.includes("Actual exit fill") && labels.includes("Stop")
      ? "Actual exit fill = Stop"
      : fourHourBoundary && labels.includes("C2 acceptance")
        ? `${fourHourBoundary} = C2 acceptance`
        : labels.join(" = ");
    return { ...preferred, label };
  });
}

function formatTaipeiShort(ms: number): string {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false,
    timeZone: "Asia/Taipei",
  }).format(new Date(ms)).replace(/,\s*/, " ");
}

function formatTaipeiEvent(ms: number): string {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false,
    timeZone: "Asia/Taipei",
  }).format(new Date(ms)).replace(/,\s*/, " ");
}

function formatReferenceClock(ms: number, timeZone: "UTC" | "America/New_York"): string {
  return new Intl.DateTimeFormat("en-GB", {
    hour: "2-digit", minute: "2-digit", hour12: false, timeZone,
  }).format(new Date(ms));
}

function referenceSummary(trade: DailyRangeClosedChartSnapshotTrade): string {
  const timeZone = trade.referenceTimezone ?? "UTC";
  const zoneLabel = timeZone === "America/New_York" ? "New York" : "UTC";
  const window = finite(trade.referenceRangeOpenTime) && finite(trade.referenceRangeCloseTime)
    ? `${formatReferenceClock(trade.referenceRangeOpenTime, timeZone)}–${formatReferenceClock(trade.referenceRangeCloseTime, timeZone)}`
    : "persisted";
  return `4H ref ${window} ${zoneLabel} · H ${formatOverlayPrice(trade.rangeHigh)} / L ${formatOverlayPrice(trade.rangeLow)}`;
}

function calculateEma(candles: readonly SnapshotCandle[], period: number): OverlayPoint[] {
  if (candles.length < period) return [];
  const seed = candles.slice(0, period).reduce((sum, candle) => sum + candle.close, 0) / period;
  const multiplier = 2 / (period + 1);
  let value = seed;
  const points: OverlayPoint[] = [{ openTime: candles[period - 1]!.openTime, value }];
  for (let index = period; index < candles.length; index += 1) {
    value = (candles[index]!.close - value) * multiplier + value;
    points.push({ openTime: candles[index]!.openTime, value });
  }
  return points;
}

function latestStructuralLine(candles: readonly SnapshotCandle[], kind: StructuralLine["kind"]): StructuralLine | null {
  const pivots: OverlayPoint[] = [];
  const radius = 2;
  for (let index = radius; index < candles.length - radius; index += 1) {
    const candidate = candles[index]!;
    const candidateValue = kind === "RESISTANCE" ? candidate.high : candidate.low;
    let valid = true;
    for (let offset = 1; offset <= radius; offset += 1) {
      const before = candles[index - offset]!;
      const after = candles[index + offset]!;
      const beforeValue = kind === "RESISTANCE" ? before.high : before.low;
      const afterValue = kind === "RESISTANCE" ? after.high : after.low;
      if (kind === "RESISTANCE" ? candidateValue <= beforeValue || candidateValue <= afterValue : candidateValue >= beforeValue || candidateValue >= afterValue) {
        valid = false;
        break;
      }
    }
    if (valid) pivots.push({ openTime: candidate.openTime, value: candidateValue });
  }
  if (pivots.length < 2) return null;
  const first = pivots[pivots.length - 2]!;
  const second = pivots[pivots.length - 1]!;
  const elapsed = second.openTime - first.openTime;
  if (!(elapsed > 0)) return null;
  const latest = candles.at(-1)!;
  const slope = (second.value - first.value) / elapsed;
  const points = [first, second];
  if (latest.openTime > second.openTime) points.push({ openTime: latest.openTime, value: second.value + slope * (latest.openTime - second.openTime) });
  return { kind, points };
}

function linePoints(points: readonly OverlayPoint[], x: (value: number) => number, y: (value: number) => number, start: number, end: number): string {
  return points
    .filter((point) => point.openTime >= start && point.openTime <= end && finite(point.value))
    .map((point) => `${x(point.openTime).toFixed(2)},${y(point.value).toFixed(2)}`)
    .join(" ");
}

function candleAtOrNearest(candles: readonly SnapshotCandle[], at: number): SnapshotCandle | null {
  let selected: SnapshotCandle | null = null;
  let distance = Number.POSITIVE_INFINITY;
  for (const candle of candles) {
    const nextDistance = Math.abs(candle.openTime - at);
    if (nextDistance < distance) {
      selected = candle;
      distance = nextDistance;
    }
  }
  return selected;
}

/** A persisted arm event may only be shown on the candle that really contains it. */
function containingCompletedCandle(candles: readonly SnapshotCandle[], at: number): SnapshotCandle | null {
  return candles.find((candle) => at >= candle.openTime && at <= candle.closeTime) ?? null;
}

function renderPanel(input: {
  x: number;
  y: number;
  width: number;
  height: number;
  title: string;
  subtitle: string;
  candles: SnapshotCandle[];
  allCandles: SnapshotCandle[];
  intervalMs: number;
  viewportStart: number;
  viewportEnd: number;
  levels: PriceLevel[];
  markers: SnapshotMarker[];
  events?: SnapshotEvent[];
  zones?: RiskZone[];
  partialInterval?: PartialCandleInterval | null;
  resolutionNote?: string | null;
  showStructure?: boolean;
}): string {
  const { x: outerX, y: outerY, width, height, title, subtitle, candles, allCandles, intervalMs, viewportStart, viewportEnd, levels, markers, events = [], zones = [], partialInterval = null, resolutionNote = null, showStructure = false } = input;
  const left = outerX + 72;
  const right = outerX + width - 148;
  // C1/C2/entry/arm/exit live in a separate event rail. Nothing verbose is
  // written over the final candles, where event labels used to collide.
  const top = outerY + 82;
  // Keep chart labels and the legend in their own footer space. Previously
  // both occupied the same band, which made the time axis unreadable.
  const bottom = outerY + height - 102;
  const plotWidth = Math.max(1, right - left);
  const plotHeight = Math.max(1, bottom - top);
  const timeStart = Math.min(viewportStart, viewportEnd - intervalMs);
  const timeEnd = Math.max(viewportEnd, timeStart + intervalMs);
  const visible = candles.filter((candle) => candle.closeTime + 1 > timeStart && candle.openTime <= timeEnd);
  const ema20 = calculateEma(allCandles, 20);
  const ema50 = calculateEma(allCandles, 50);
  const resistance = showStructure ? latestStructuralLine(allCandles, "RESISTANCE") : null;
  const support = showStructure ? latestStructuralLine(allCandles, "SUPPORT") : null;
  const displayedLevels = consolidateCoincidentLevels(levels);
  const values = [
    ...visible.flatMap((candle) => [candle.high, candle.low]),
    ...displayedLevels.map((level) => level.price),
    ...ema20.filter((point) => point.openTime >= timeStart && point.openTime <= timeEnd).map((point) => point.value),
    ...ema50.filter((point) => point.openTime >= timeStart && point.openTime <= timeEnd).map((point) => point.value),
    ...(resistance?.points ?? []).map((point) => point.value),
    ...(support?.points ?? []).map((point) => point.value),
  ].filter(positive);
  const minimum = values.length ? Math.min(...values) : 0;
  const maximum = values.length ? Math.max(...values) : 1;
  const padding = Math.max((maximum - minimum) * 0.1, maximum * 0.001, 1e-10);
  const low = minimum - padding;
  const high = maximum + padding;
  const x = (at: number): number => left + (at - timeStart) / (timeEnd - timeStart) * plotWidth;
  const y = (price: number): number => top + (high - price) / (high - low) * plotHeight;
  const clipId = `clip-${Math.round(outerX)}-${Math.round(outerY)}`;
  const horizontalGrid = Array.from({ length: 5 }, (_, index) => {
    const ratio = index / 4;
    const price = high - ratio * (high - low);
    const yy = top + ratio * plotHeight;
    return `<line x1="${left}" y1="${yy}" x2="${right}" y2="${yy}" stroke="${COLORS.grid}" stroke-width="1" opacity="0.72"/><text x="${right + 10}" y="${yy + 4}" fill="${COLORS.dim}" font-size="13">${escapeXml(formatPrice(price))}</text>`;
  }).join("");
  const verticalGrid = Array.from({ length: 5 }, (_, index) => {
    const ratio = index / 4;
    const at = timeStart + ratio * (timeEnd - timeStart);
    const xx = left + ratio * plotWidth;
    return `<line x1="${xx}" y1="${top}" x2="${xx}" y2="${bottom}" stroke="${COLORS.grid}" stroke-width="1" opacity="0.5"/><text x="${xx}" y="${bottom + 22}" fill="${COLORS.dim}" font-size="12" text-anchor="middle">${escapeXml(formatTaipeiShort(at))}</text>`;
  }).join("");
  const zoneSvg = zones.map((zone) => {
    const from = Math.min(y(zone.from), y(zone.to));
    const to = Math.max(y(zone.from), y(zone.to));
    return `<rect x="${x(viewportStart)}" y="${from}" width="${Math.max(1, x(viewportEnd) - x(viewportStart))}" height="${Math.max(1, to - from)}" fill="${zone.color}" opacity="0.12"/>`;
  }).join("");
  const partialIntervalSvg = (() => {
    if (!partialInterval) return "";
    const start = Math.max(timeStart, partialInterval.start);
    const end = Math.min(timeEnd, partialInterval.end);
    if (!(end > start)) return "";
    const leftX = x(start);
    const rightX = x(end);
    return `<g data-execution-clarity="partial-5m"><rect x="${leftX}" y="${top}" width="${Math.max(1, rightX - leftX)}" height="${plotHeight}" fill="${COLORS.partial}" opacity="0.10" stroke="${COLORS.partial}" stroke-width="1" stroke-dasharray="3 3"/><line x1="${rightX}" y1="${top}" x2="${rightX}" y2="${bottom}" stroke="${COLORS.partial}" stroke-width="1" stroke-dasharray="4 4" opacity="0.9"/></g>`;
  })();
  const levelSvg = displayedLevels.map((level) => {
    const yy = y(level.price);
    return `<line x1="${left}" y1="${yy}" x2="${right}" y2="${yy}" stroke="${level.color}" stroke-width="1.5" stroke-dasharray="${level.dash ?? "7 6"}" opacity="0.95"/>`;
  }).join("");
  const candleSvg = visible.map((candle) => {
    const durationMs = Math.max(1, candle.closeTime + 1 - candle.openTime);
    const xx = x(candle.openTime + durationMs / 2);
    const candleWidth = Math.max(1.25, Math.min(14, durationMs / (timeEnd - timeStart) * plotWidth * 0.72));
    const up = candle.close >= candle.open;
    const color = up ? COLORS.up : COLORS.down;
    const openY = y(candle.open);
    const closeY = y(candle.close);
    const bodyY = Math.min(openY, closeY);
    const bodyHeight = Math.max(1, Math.abs(openY - closeY));
    return `<line x1="${xx}" y1="${y(candle.high)}" x2="${xx}" y2="${y(candle.low)}" stroke="${color}" stroke-width="1.2"/><rect x="${xx - candleWidth / 2}" y="${bodyY}" width="${candleWidth}" height="${bodyHeight}" fill="${color}"/>`;
  }).join("");
  const emaSvg = [
    { points: ema20, color: COLORS.ema20, label: "EMA20" },
    { points: ema50, color: COLORS.ema50, label: "EMA50" },
  ].map((line) => {
    const points = linePoints(line.points, x, y, timeStart, timeEnd);
    return points ? `<polyline points="${points}" fill="none" stroke="${line.color}" stroke-width="2"/>` : "";
  }).join("");
  const structureSvg = [resistance, support].filter((line): line is StructuralLine => line !== null).map((line) => {
    const points = linePoints(line.points, x, y, timeStart, timeEnd);
    const color = line.kind === "RESISTANCE" ? COLORS.resistance : COLORS.support;
    return points ? `<polyline points="${points}" fill="none" stroke="${color}" stroke-width="2.2"/>` : "";
  }).join("");
  const markerSvg = markers.map((marker) => {
    if (marker.at < timeStart || marker.at > timeEnd || !positive(marker.price)) return "";
    const eventCandle = marker.candleOpenTime === undefined
      ? null
      : visible.find((candle) => candle.openTime === marker.candleOpenTime)
        // A persisted ARM must never silently move to a neighbouring candle.
        // C1/C2 are legacy-compatible trigger markers and retain their old
        // rendering fallback for already-captured chart assets.
        ?? (marker.eventId === "ARM" ? null : candleAtOrNearest(visible, marker.candleOpenTime));
    const xx = eventCandle
      ? x(eventCandle.openTime + (eventCandle.closeTime + 1 - eventCandle.openTime) / 2)
      : x(marker.at);
    const exactPriceY = y(marker.price);
    const up = marker.position === "above";
    const down = marker.position === "below";
    // C1/C2/ARM identify a complete candle, so draw them at the wick extreme
    // of that candle. Their exact event time stays explicit in the rail; the
    // visual marker must not float between two bars.
    const candleAnchorY = eventCandle && (up || down)
      ? y(up ? eventCandle.high : eventCandle.low)
      : exactPriceY;
    const markerY = Math.min(bottom - 12, Math.max(top + 12, candleAnchorY + (marker.visualOffsetY ?? 0)));
    const labelPosition = marker.labelPosition ?? (down ? "below" : "above");
    const labelY = labelPosition === "above" ? Math.max(top + 14, markerY - 16) : Math.min(bottom - 6, markerY + 24);
    const triangle = up
      ? `${xx},${markerY - 6} ${xx - 5},${markerY + 4} ${xx + 5},${markerY + 4}`
      : down
        ? `${xx},${markerY + 6} ${xx - 5},${markerY - 4} ${xx + 5},${markerY - 4}`
        : "";
    const pointColor = marker.pointColor ?? marker.color;
    const shape = marker.position === "middle"
      ? `<circle cx="${xx}" cy="${markerY}" r="5" fill="${pointColor}" stroke="#071016" stroke-width="2"/>`
      : `<polygon points="${triangle}" fill="${pointColor}" stroke="#071016" stroke-width="1"/>`;
    const stem = Math.abs(markerY - candleAnchorY) > 0.1
      ? `<line x1="${xx}" y1="${candleAnchorY}" x2="${xx}" y2="${markerY}" stroke="${pointColor}" stroke-width="1.2" stroke-dasharray="2 2"/>`
      : "";
    const labelAnchor = marker.labelAnchor ?? "start";
    const labelX = xx + (labelAnchor === "end" ? -8 : 8);
    const label = marker.label
      ? `<text x="${labelX}" y="${labelY}" fill="${marker.color}" font-size="12" font-weight="700" text-anchor="${labelAnchor}">${escapeXml(marker.label)}</text>`
      : "";
    const markerTagPosition = marker.markerTagPosition ?? (down ? "below" : "above");
    const markerTagY = markerTagPosition === "below"
      ? Math.min(bottom - 5, markerY + 19)
      : Math.max(top + 12, markerY - 10);
    const markerTag = marker.markerTag
      ? `<text x="${xx}" y="${markerTagY}" fill="${marker.color}" font-size="10" font-weight="700" text-anchor="middle">${escapeXml(marker.markerTag)}</text>`
      : "";
    const candleData = eventCandle && (up || down)
      ? ` data-marker-candle-open="${eventCandle.openTime}" data-marker-anchor="${up ? "high" : "low"}"`
      : "";
    return `<g data-execution-marker="${marker.eventId ?? "event"}"${candleData}>${stem}${shape}${markerTag}${label}</g>`;
  }).join("");
  const railEvents = events.slice(0, 5);
  const railGap = 8;
  const railWidth = railEvents.length
    ? (width - 32 - railGap * (railEvents.length - 1)) / railEvents.length
    : 0;
  const eventRailSvg = railEvents.map((event, index) => {
    const xx = outerX + 16 + index * (railWidth + railGap);
    const yy = outerY + 48;
    const label = `${event.label} · ${formatTaipeiEvent(event.at)} · ${formatOverlayPrice(event.price)}`;
    const pointColor = event.pointColor ?? event.color;
    return `<rect x="${xx}" y="${yy}" width="${railWidth}" height="20" rx="4" fill="#10212a" stroke="${COLORS.border}"/><circle cx="${xx + 10}" cy="${yy + 10}" r="3" fill="${pointColor}"/><text x="${xx + 18}" y="${yy + 14}" fill="${COLORS.text}" font-size="11">${escapeXml(label)}</text>`;
  }).join("");
  const legendRows = [
    ...displayedLevels.map((level) => ({ color: level.color, text: `${level.label} ${formatOverlayPrice(level.price)}` })),
    ...(resolutionNote ? [{ color: COLORS.acceptance, text: resolutionNote }] : []),
    ...(partialInterval ? [{ color: COLORS.partial, text: `${partialInterval.intervalLabel} partial to exit · no synthetic candle` }] : []),
    { color: COLORS.ema20, text: "EMA20" },
    { color: COLORS.ema50, text: "EMA50" },
    ...(showStructure ? [{ color: COLORS.resistance, text: "Structural resistance" }, { color: COLORS.support, text: "Structural support" }] : []),
  ];
  const legendSvg = legendRows.slice(0, 12).map((item, index) => {
    const column = index % 4;
    const row = Math.floor(index / 4);
    const xx = outerX + 16 + column * 375;
    const yy = outerY + height - 52 + row * 16;
    const pillWidth = Math.min(330, 30 + item.text.length * 7);
    return `<rect x="${xx}" y="${yy - 14}" width="${pillWidth}" height="19" rx="4" fill="#10212a" stroke="${COLORS.border}"/><rect x="${xx + 8}" y="${yy - 7}" width="8" height="3" fill="${item.color}"/><text x="${xx + 22}" y="${yy}" fill="${COLORS.text}" font-size="11">${escapeXml(item.text)}</text>`;
  }).join("");
  return `<g>
    <rect x="${outerX}" y="${outerY}" width="${width}" height="${height}" rx="8" fill="${COLORS.panel}" stroke="${COLORS.border}"/>
    <text x="${outerX + 16}" y="${outerY + 22}" fill="${COLORS.text}" font-size="16" font-weight="700">${escapeXml(title)}</text>
    <text x="${outerX + 16}" y="${outerY + 39}" fill="${COLORS.dim}" font-size="11">${escapeXml(subtitle)}</text>
    ${eventRailSvg}
    <clipPath id="${clipId}"><rect x="${left}" y="${top}" width="${plotWidth}" height="${plotHeight}"/></clipPath>
    ${horizontalGrid}${verticalGrid}
    <g clip-path="url(#${clipId})">${zoneSvg}${levelSvg}${structureSvg}${candleSvg}${emaSvg}${markerSvg}</g>
    ${legendSvg}
  </g>`;
}

function snapshotAssetFile(tradeId: string): string | null {
  return /^[a-z0-9-]{4,64}$/i.test(tradeId) ? `${tradeId}.svg` : null;
}

function unavailableSnapshot(requestedAt: string, entryAt: string | null, exitAt: string | null, reason: string): DailyRangeClosedChartSnapshot {
  return {
    version: DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION,
    status: "UNAVAILABLE",
    requestedAt,
    capturedAt: null,
    source: "BINANCE_USDM_COMPLETED_CANDLES",
    entryAt,
    exitAt,
    assetFile: null,
    mimeType: null,
    fiveMinuteCandleCount: 0,
    fourHourCandleCount: 0,
    reason,
  };
}

export function pendingDailyRangeClosedChartSnapshot(trade: Pick<DailyRangeClosedChartSnapshotTrade, "entryFilledAt" | "entrySubmittedAt" | "exitTimestamp">, requestedAt: string): DailyRangeClosedChartSnapshot {
  return {
    version: DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION,
    status: "PENDING",
    requestedAt,
    capturedAt: null,
    source: "BINANCE_USDM_COMPLETED_CANDLES",
    entryAt: trade.entryFilledAt ?? trade.entrySubmittedAt ?? null,
    exitAt: trade.exitTimestamp ?? null,
    assetFile: null,
    mimeType: null,
    fiveMinuteCandleCount: 0,
    fourHourCandleCount: 0,
    reason: null,
  };
}

export function renderDailyRangeClosedChartSvg(input: {
  trade: DailyRangeClosedChartSnapshotTrade;
  fiveMinuteCandles: SnapshotCandle[];
  /** Fully completed post-C2 1m candles only; boundary candles are never inferred. */
  oneMinuteCandles?: SnapshotCandle[];
  /** Preserved in the input shape for old callers; 4h remains a reference, never a second chart. */
  fourHourCandles: SnapshotCandle[];
  entryAtMs: number;
  exitAtMs: number;
}): string {
  const { trade, fiveMinuteCandles, oneMinuteCandles = [], entryAtMs, exitAtMs } = input;
  const routeLabel = trade.entryPolicy === "FADE" ? "FADE" : trade.entryPolicy === "CONTINUATION" ? "CONTINUATION" : "LEGACY CONTINUATION";
  const directionText = trade.breakoutDirection ? ` · breakout ${trade.breakoutDirection}` : "";
  const signalStart = Math.min(
    entryAtMs,
    trade.confirmationBar1.openTime,
    trade.confirmationBar2.openTime,
  );
  const fiveMinuteStart = Math.min(
    signalStart - FIVE_MINUTE_EMA_CONTEXT_BARS * FIVE_MINUTE_MS,
    fiveMinuteCandles[0]?.openTime ?? signalStart,
  );
  const isDownBreakout = trade.breakoutDirection === "DOWN" || (!trade.breakoutDirection && trade.direction === "SHORT");
  const c1CloseAt = trade.confirmationBar1.openTime + FIVE_MINUTE_MS;
  const c2CloseAt = trade.confirmationBar2.openTime + FIVE_MINUTE_MS;
  const executionCandles = mixedExecutionCandles({
    fiveMinuteCandles,
    oneMinuteCandles,
    c2CloseAt,
    exitAt: exitAtMs,
  });
  const armAtMs = toMs(trade.fadeRTrail?.trailArmedAt);
  const armThresholdR = trade.fadeRTrail?.armThresholdR;
  const armCandle = armAtMs === null
    ? null
    : containingCompletedCandle(executionCandles.candles, armAtMs);
  // The marker itself is attached to the real candle wick. This frozen
  // threshold price is only used in the event rail, never inferred from a
  // later peak/current mark.
  const armThresholdPrice = armThresholdR != null && finite(armThresholdR)
    && positive(trade.initialRiskPrice) && positive(trade.entryFillPrice)
    ? trade.direction === "LONG"
      ? trade.entryFillPrice! + armThresholdR * trade.initialRiskPrice
      : trade.entryFillPrice! - armThresholdR * trade.initialRiskPrice
    : null;
  const armMarker = armCandle !== null && armAtMs !== null
    ? {
      label: "",
      at: armAtMs,
      price: armThresholdPrice ?? trade.entryFillPrice!,
      color: COLORS.entry,
      pointColor: EXECUTION_MARKER_POINT_COLOR,
      position: "above" as const,
      markerTag: "ARM",
      markerTagPosition: "above" as const,
      visualOffsetY: -14,
      candleOpenTime: armCandle.openTime,
      eventId: "ARM" as const,
    }
    : null;
  const breakoutReference = isDownBreakout
    ? { label: "4H breakdown", price: trade.rangeLow, color: COLORS.rangeLow }
    : { label: "4H breakout", price: trade.rangeHigh, color: COLORS.rangeHigh };
  const acceptanceLevel: PriceLevel = {
    label: "C2 acceptance",
    price: trade.confirmationBar2.close,
    color: COLORS.acceptance,
    dash: "3 4",
  };
  // The snapshot is intentionally a 5m execution review. The Daily Range
  // reference remains as one breakout level; the opposite 4H boundary must
  // never flatten the candles or dominate the chart scale.
  const executionLevels: PriceLevel[] = [
    breakoutReference,
    acceptanceLevel,
    { label: "Entry", price: trade.entryFillPrice!, color: COLORS.entry },
    ...(positive(trade.stopPrice) ? [{ label: "Stop", price: trade.stopPrice, color: COLORS.stop }] : []),
    ...(positive(trade.takeProfitPrice) ? [{ label: "TP trigger", price: trade.takeProfitPrice, color: COLORS.takeProfit }] : []),
    { label: "Actual exit fill", price: trade.exitPrice!, color: COLORS.exit },
  ];
  const breakoutPosition = isDownBreakout ? "below" : "above" as const;
  const c2Position = isDownBreakout ? "above" : "below" as const;
  const markers: SnapshotMarker[] = [
    {
      label: "",
      at: c1CloseAt,
      price: trade.confirmationBar1.close,
      color: breakoutReference.color,
      position: breakoutPosition,
      labelAnchor: "end",
      labelPosition: "above",
      markerTag: "C1",
      markerTagPosition: "above",
      visualOffsetY: breakoutPosition === "above" ? -14 : 14,
      candleOpenTime: trade.confirmationBar1.openTime,
      eventId: "C1",
    },
    {
      label: "",
      at: c2CloseAt,
      price: trade.confirmationBar2.close,
      color: COLORS.acceptance,
      position: c2Position,
      labelAnchor: "start",
      labelPosition: "above",
      markerTag: "C2",
      markerTagPosition: c2Position === "above" ? "above" : "below",
      visualOffsetY: c2Position === "above" ? -14 : 14,
      candleOpenTime: trade.confirmationBar2.openTime,
      eventId: "C2",
    },
    { label: "", at: entryAtMs, price: trade.entryFillPrice!, color: COLORS.entry, pointColor: EXECUTION_MARKER_POINT_COLOR, position: "middle", labelAnchor: "end", labelPosition: "below", eventId: "ENTRY" },
    ...(armMarker ? [armMarker] : []),
    { label: "", at: exitAtMs, price: trade.exitPrice!, color: COLORS.exit, pointColor: EXECUTION_MARKER_POINT_COLOR, position: "middle", labelAnchor: "start", labelPosition: "above", eventId: "EXIT" },
  ];
  const exitIsStop = positive(trade.stopPrice) && Math.abs(trade.exitPrice! - trade.stopPrice) <= Math.max(1e-10, Math.abs(trade.exitPrice!) * 1e-10);
  const events: SnapshotEvent[] = [
    { label: "C1 breakout close", at: c1CloseAt, price: trade.confirmationBar1.close, color: breakoutReference.color },
    { label: "C2 acceptance close", at: c2CloseAt, price: trade.confirmationBar2.close, color: COLORS.acceptance },
    { label: `Entry ${trade.direction} fill`, at: entryAtMs, price: trade.entryFillPrice!, color: COLORS.entry, pointColor: EXECUTION_MARKER_POINT_COLOR },
    ...(armMarker && armThresholdPrice !== null
      ? [{ label: `MFE arm +${armThresholdR!.toFixed(2)}R`, at: armAtMs!, price: armThresholdPrice, color: COLORS.entry, pointColor: EXECUTION_MARKER_POINT_COLOR }]
      : armMarker
        ? [{ label: "MFE arm", at: armAtMs!, price: trade.entryFillPrice!, color: COLORS.entry, pointColor: EXECUTION_MARKER_POINT_COLOR }]
        : []),
    { label: exitIsStop ? "Exit / stop fill" : "Exit fill", at: exitAtMs, price: trade.exitPrice!, color: COLORS.exit, pointColor: EXECUTION_MARKER_POINT_COLOR },
  ];
  const finalIntervalMs = executionCandles.usesOneMinuteAfterC2 ? 60_000 : FIVE_MINUTE_MS;
  const activeIntervalStart = Math.floor(exitAtMs / finalIntervalMs) * finalIntervalMs;
  const finalIntervalLabel: PartialCandleInterval["intervalLabel"] = executionCandles.usesOneMinuteAfterC2 ? "1m" : "5m";
  const partialInterval: PartialCandleInterval | null = exitAtMs > activeIntervalStart
    ? { start: activeIntervalStart, end: exitAtMs, intervalLabel: finalIntervalLabel }
    : null;
  const zones: RiskZone[] = [
    ...(positive(trade.stopPrice) ? [{ from: trade.entryFillPrice!, to: trade.stopPrice, color: COLORS.stop, label: "risk to SL" }] : []),
    ...(positive(trade.takeProfitPrice) ? [{ from: trade.entryFillPrice!, to: trade.takeProfitPrice, color: COLORS.takeProfit, label: "target to TP" }] : []),
  ];
  const execution = renderPanel({
    x: 32, y: 74, width: 1536, height: 754,
    title: executionCandles.usesOneMinuteAfterC2 ? "5m → 1m · actual execution path" : "5m · actual execution path",
    subtitle: `${trade.symbol} · ${trade.direction} · ${routeLabel}${directionText} · ${referenceSummary(trade)}`,
    candles: executionCandles.candles,
    allCandles: fiveMinuteCandles,
    intervalMs: FIVE_MINUTE_MS,
    viewportStart: fiveMinuteStart,
    viewportEnd: exitAtMs + CLOSE_LABEL_RIGHT_PADDING_BARS * FIVE_MINUTE_MS,
    levels: executionLevels,
    markers,
    events,
    zones,
    partialInterval,
    resolutionNote: executionCandles.usesOneMinuteAfterC2 ? "1m candles after C2 close" : null,
  });
  const chartResolution = executionCandles.usesOneMinuteAfterC2 ? "5M/1M" : "5M";
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="860" viewBox="0 0 1600 860" role="img" aria-labelledby="snapshot-title snapshot-desc" data-execution-clarity="v7">
  <title id="snapshot-title">${escapeXml(`${trade.symbol} Daily Range ${chartResolution} execution snapshot`)}</title>
  <desc id="snapshot-desc">Readable execution view from completed Binance USD-M candles at or before the confirmed exit. C1 and C2 are close-of-bar events; entry and exit are exact exchange fills. A white ARM marker appears only for the persisted R-trail arm and its containing completed candle. When available, fully completed 1m candles begin after C2. The final unfinished interval is a neutral timing band, never a synthetic candle.</desc>
  <rect width="1600" height="860" fill="${COLORS.background}"/>
  <text x="32" y="32" fill="${COLORS.text}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="20" font-weight="700">DAILY RANGE 4H · ${chartResolution} TRADE SNAPSHOT</text>
  <text x="32" y="54" fill="${COLORS.dim}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="12">Completed candles through confirmed exit · 4H is the strategy reference, not a second chart</text>
  <g font-family="ui-monospace, SFMono-Regular, Menlo, monospace">${execution}</g>
</svg>`;
}

export async function captureDailyRangeClosedChartSnapshot(input: {
  directory: string;
  client: DailyRangeClosedChartSnapshotClient;
  trade: DailyRangeClosedChartSnapshotTrade;
  nowMs?: () => number;
}): Promise<DailyRangeClosedChartSnapshot> {
  const requestedAt = new Date(input.nowMs?.() ?? Date.now()).toISOString();
  const entryAtMs = toMs(input.trade.entryFilledAt ?? input.trade.entrySubmittedAt);
  const exitAtMs = toMs(input.trade.exitTimestamp);
  if (entryAtMs === null || exitAtMs === null || exitAtMs < entryAtMs || !positive(input.trade.entryFillPrice) || !positive(input.trade.exitPrice)) {
    return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "ordered confirmed entry and exit fills are required");
  }
  const confirmationBar1 = asSnapshotCandle(input.trade.confirmationBar1);
  const confirmationBar2 = asSnapshotCandle(input.trade.confirmationBar2);
  if (!confirmationBar1 || !confirmationBar2) {
    return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "persisted C1/C2 execution bars are required for a truthful close-time image");
  }
  const assetFile = snapshotAssetFile(input.trade.tradeId);
  if (!assetFile) return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "invalid trade id for snapshot asset");
  const signalStart = Math.min(confirmationBar1.openTime, confirmationBar2.openTime, entryAtMs);
  const fiveMinuteStart = Math.max(0, signalStart - FIVE_MINUTE_EMA_CONTEXT_BARS * FIVE_MINUTE_MS);
  const fiveMinuteEnd = Math.floor((exitAtMs - 1) / FIVE_MINUTE_MS) * FIVE_MINUTE_MS;
  try {
    const fiveMinuteRows = await input.client.getKlines(input.trade.symbol, "5m", { startTime: fiveMinuteStart, endTime: fiveMinuteEnd });
    const fiveMinuteCandles = distinctCompletedCandles(
      [...fiveMinuteRows, confirmationBar1, confirmationBar2],
      fiveMinuteStart,
      exitAtMs,
    );
    if (fiveMinuteCandles.length === 0) {
      return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "no completed 5m USD-M candle is available before the exit fill");
    }
    // The post-C2 review is a best-effort visual refinement. A failed or
    // gapped 1m fetch must never downgrade an otherwise valid 5m close image.
    let oneMinuteCandles: SnapshotCandle[] = [];
    try {
      const c2CloseAt = confirmationBar2.openTime + FIVE_MINUTE_MS;
      const oneMinuteRows = await input.client.getKlines(input.trade.symbol, "1m", {
        startTime: c2CloseAt,
        endTime: exitAtMs - 1,
      });
      oneMinuteCandles = distinctCompletedCandles(oneMinuteRows, c2CloseAt, exitAtMs);
    } catch {
      oneMinuteCandles = [];
    }
    const renderedCandles = mixedExecutionCandles({
      fiveMinuteCandles,
      oneMinuteCandles,
      c2CloseAt: confirmationBar2.openTime + FIVE_MINUTE_MS,
      exitAt: exitAtMs,
    });
    const svg = renderDailyRangeClosedChartSvg({ trade: input.trade, fiveMinuteCandles, oneMinuteCandles, fourHourCandles: [], entryAtMs, exitAtMs });
    const root = resolve(input.directory);
    mkdirSync(root, { recursive: true });
    const file = resolve(root, assetFile);
    if (!file.startsWith(root + sep)) {
      return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "snapshot path escaped its archive directory");
    }
    const temporary = `${file}.tmp-${process.pid}-${Date.now()}`;
    writeFileSync(temporary, svg, "utf8");
    renameSync(temporary, file);
    return {
      version: DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION,
      status: "CAPTURED",
      requestedAt,
      capturedAt: new Date(input.nowMs?.() ?? Date.now()).toISOString(),
      source: "BINANCE_USDM_COMPLETED_CANDLES",
      entryAt: input.trade.entryFilledAt ?? input.trade.entrySubmittedAt,
      exitAt: input.trade.exitTimestamp,
      assetFile,
      mimeType: "image/svg+xml",
      fiveMinuteCandleCount: fiveMinuteCandles.length,
      oneMinuteCandleCount: renderedCandles.usesOneMinuteAfterC2 ? oneMinuteCandles.length : 0,
      fourHourCandleCount: 0,
      reason: null,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      ...pendingDailyRangeClosedChartSnapshot(input.trade, requestedAt),
      reason: `snapshot source unavailable: ${message}`,
    };
  }
}

type LegacySvgPoint = Readonly<{ x: number; y: number }>;
type LegacyCandleWick = Readonly<{ x: number; highY: number; lowY: number }>;

function parseLegacySvgPoint(value: string): LegacySvgPoint | null {
  const [rawX, rawY] = value.split(",", 2);
  const x = Number(rawX);
  const y = Number(rawY);
  return Number.isFinite(x) && Number.isFinite(y) ? { x, y } : null;
}

function legacyTriangleCentres(svg: string): LegacySvgPoint[] {
  const matches = [...svg.matchAll(/<polygon points="([^"]+)" fill="[^"]+" stroke="#071016" stroke-width="1"\/>/g)];
  return matches.flatMap((match) => {
    const points = match[1]!.trim().split(/\s+/).map(parseLegacySvgPoint);
    const tip = points[0];
    const base = points[1];
    if (!tip || !base) return [];
    return [{ x: tip.x, y: tip.y < base.y ? tip.y + 6 : tip.y - 6 }];
  });
}

function legacyExecutionPoints(svg: string): LegacySvgPoint[] {
  const matches = [...svg.matchAll(/<circle cx="([^"]+)" cy="([^"]+)" r="5" fill="[^"]+" stroke="#071016" stroke-width="2"\/>/g)];
  return matches.flatMap((match) => {
    const x = Number(match[1]);
    const y = Number(match[2]);
    return Number.isFinite(x) && Number.isFinite(y) ? [{ x, y }] : [];
  });
}

function legacyCandleWicks(svg: string): LegacyCandleWick[] {
  const matches = [...svg.matchAll(/<line x1="([^"]+)" y1="([^"]+)" x2="([^"]+)" y2="([^"]+)" stroke="#(?:5ce4a6|ff777d)" stroke-width="1\.2"\/>/g)];
  return matches.flatMap((match) => {
    const x1 = Number(match[1]);
    const y1 = Number(match[2]);
    const x2 = Number(match[3]);
    const y2 = Number(match[4]);
    if (![x1, y1, x2, y2].every(Number.isFinite) || Math.abs(x1 - x2) > 0.01) return [];
    return [{ x: x1, highY: Math.min(y1, y2), lowY: Math.max(y1, y2) }];
  });
}

/** A legacy marker was written on the bar-close boundary; pick the candle immediately to its left. */
function legacyTriggerCandle(wicks: readonly LegacyCandleWick[], eventX: number): LegacyCandleWick | null {
  const before = wicks.filter((wick) => wick.x <= eventX + 0.01);
  if (before.length > 0) return before.reduce((selected, wick) => wick.x > selected.x ? wick : selected);
  return wicks.reduce<LegacyCandleWick | null>(
    (selected, wick) => selected === null || Math.abs(wick.x - eventX) < Math.abs(selected.x - eventX) ? wick : selected,
    null,
  );
}

function legacyTaggedTriangle(input: {
  point: LegacySvgPoint;
  candle?: LegacyCandleWick | null;
  position: "above" | "below";
  color: string;
  tag: string;
  top: number;
  bottom: number;
}): string {
  const anchorX = input.candle?.x ?? input.point.x;
  const anchorY = input.candle
    ? input.position === "above" ? input.candle.highY : input.candle.lowY
    : input.point.y;
  const visualY = Math.min(input.bottom - 12, Math.max(input.top + 12, anchorY + (input.position === "above" ? -14 : 14)));
  const triangle = input.position === "above"
    ? `${anchorX},${visualY - 6} ${anchorX - 5},${visualY + 4} ${anchorX + 5},${visualY + 4}`
    : `${anchorX},${visualY + 6} ${anchorX - 5},${visualY - 4} ${anchorX + 5},${visualY - 4}`;
  const tagY = input.position === "above"
    ? Math.max(input.top + 12, visualY - 10)
    : Math.min(input.bottom - 5, visualY + 19);
  const candleData = input.candle
    ? ` data-marker-candle-x="${input.candle.x}" data-marker-anchor="${input.position === "above" ? "high" : "low"}"`
    : "";
  return `<g data-execution-marker="${input.tag}"${candleData}><line x1="${anchorX}" y1="${anchorY}" x2="${anchorX}" y2="${visualY}" stroke="${input.color}" stroke-width="1.2" stroke-dasharray="2 2"/><polygon points="${triangle}" fill="${input.color}" stroke="#071016" stroke-width="1"/><text x="${anchorX}" y="${tagY}" fill="${input.color}" font-size="10" font-weight="700" text-anchor="middle">${input.tag}</text></g>`;
}

function legacyEventRailText(svg: string, trade: DailyRangeClosedChartSnapshotTrade): string {
  const c1At = trade.confirmationBar1.openTime + FIVE_MINUTE_MS;
  const c2At = trade.confirmationBar2.openTime + FIVE_MINUTE_MS;
  const entryAt = toMs(trade.entryFilledAt ?? trade.entrySubmittedAt);
  const exitAt = toMs(trade.exitTimestamp);
  let output = svg
    .replace(/C1 breakout · [^<]*/g, "C1 breakout close · " + formatTaipeiEvent(c1At) + " · " + formatOverlayPrice(trade.confirmationBar1.close))
    .replace(/C2 acceptance · [^<]*/g, "C2 acceptance close · " + formatTaipeiEvent(c2At) + " · " + formatOverlayPrice(trade.confirmationBar2.close))
    .replace(/>Target ([0-9][0-9.,]*)</g, ">TP trigger $1<")
    .replace(/>Exit ([0-9][0-9.,]*)</g, ">Actual exit fill $1<");
  if (entryAt !== null && positive(trade.entryFillPrice)) {
    output = output.replace(/Entry (?:LONG|SHORT) · [^<]*/g, "Entry " + trade.direction + " fill · " + formatTaipeiEvent(entryAt) + " · " + formatOverlayPrice(trade.entryFillPrice));
  }
  if (exitAt !== null && positive(trade.exitPrice)) {
    output = output.replace(/Exit(?: \/ stop)? · [^<]*/g, "Exit fill · " + formatTaipeiEvent(exitAt) + " · " + formatOverlayPrice(trade.exitPrice));
  }
  // Older close-chart artifacts wrote four verbose labels directly over the
  // final candles. The v6 overlay below replaces them with non-overlapping,
  // timestamp-aware markers; retaining both would reintroduce the collision.
  return output
    .replace(/<text\b[^>]*>C1 breakout<\/text>/g, "")
    .replace(/<text\b[^>]*>C2 (?:acceptance|continuation)<\/text>/g, "")
    .replace(/<text\b[^>]*>ENTRY (?:LONG|SHORT)<\/text>/g, "")
    .replace(/<text\b[^>]*>EXIT(?: \/ STOP)?<\/text>/g, "");
}

function upgradeLegacyDailyRangeChartPresentation(svg: string, trade: DailyRangeClosedChartSnapshotTrade | undefined): string {
  if (!trade || svg.includes('data-execution-clarity="')) return svg;
  const output = legacyEventRailText(svg, trade);
  const [c1, c2] = legacyTriangleCentres(output);
  const [entry, exit] = legacyExecutionPoints(output);
  const entryAt = toMs(trade.entryFilledAt ?? trade.entrySubmittedAt);
  const exitAt = toMs(trade.exitTimestamp);
  if (!c1 || !c2 || !entry || !exit || entryAt === null || exitAt === null) return output;
  const wicks = legacyCandleWicks(output);
  const c1TriggerCandle = legacyTriggerCandle(wicks, c1.x);
  const c2TriggerCandle = legacyTriggerCandle(wicks, c2.x);
  // Replace a boundary marker only when its source candle is known. This
  // keeps malformed very-old artifacts readable instead of guessing a bar.
  const presentation = c1TriggerCandle || c2TriggerCandle
    ? output.replace(/<polygon points="[^"]+" fill="#(?:6fb3d6|f0b54b|78c8ff)" stroke="#071016" stroke-width="1"\/>/g, "")
    : output;
  const clip = /<clipPath id="([^"]+)"><rect x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)"\/><\/clipPath>/.exec(presentation);
  const plotX = Number(clip?.[2]);
  const plotTop = Number(clip?.[3]);
  const plotWidth = Number(clip?.[4]);
  const plotHeight = Number(clip?.[5]);
  if (![plotX, plotTop, plotWidth, plotHeight].every(Number.isFinite) || !(plotWidth > 0) || !(plotHeight > 0)) return output;
  const plotBottom = plotTop + plotHeight;
  const c1At = trade.confirmationBar1.openTime + FIVE_MINUTE_MS;
  const c2At = trade.confirmationBar2.openTime + FIVE_MINUTE_MS;
  const pixelsPerMs = (c2.x - c1.x) / (c2At - c1At);
  const partialStart = Math.floor(exitAt / FIVE_MINUTE_MS) * FIVE_MINUTE_MS;
  const partialStartX = Number.isFinite(pixelsPerMs) && pixelsPerMs > 0
    ? Math.max(plotX, Math.min(exit.x, exit.x - (exitAt - partialStart) * pixelsPerMs))
    : exit.x;
  const partialBand = partialStartX < exit.x
    ? `<g clip-path="url(#${clip?.[1]})"><rect x="${partialStartX}" y="${plotTop}" width="${Math.max(1, exit.x - partialStartX)}" height="${plotHeight}" fill="${COLORS.partial}" opacity="0.10" stroke="${COLORS.partial}" stroke-width="1" stroke-dasharray="3 3"/><line x1="${exit.x}" y1="${plotTop}" x2="${exit.x}" y2="${plotBottom}" stroke="${COLORS.partial}" stroke-width="1" stroke-dasharray="4 4" opacity="0.9"/></g>`
    : "";
  const isDownBreakout = trade.breakoutDirection === "DOWN" || (!trade.breakoutDirection && trade.direction === "SHORT");
  const c1Position = isDownBreakout ? "below" : "above";
  const c2Position = isDownBreakout ? "above" : "below";
  const c1Color = isDownBreakout ? COLORS.rangeLow : COLORS.rangeHigh;
  const partialLabelX = Math.max(plotX + 5, Math.min(plotX + plotWidth - 188, partialStartX + 5));
  const overlay = `
  <g data-execution-clarity="legacy-v6" pointer-events="none">
    ${partialBand}
    ${legacyTaggedTriangle({ point: c1, candle: c1TriggerCandle, position: c1Position, color: c1Color, tag: "C1", top: plotTop, bottom: plotBottom })}
    ${legacyTaggedTriangle({ point: c2, candle: c2TriggerCandle, position: c2Position, color: COLORS.acceptance, tag: "C2", top: plotTop, bottom: plotBottom })}
    <text x="${entry.x + 9}" y="${Math.max(plotTop + 12, entry.y - 11)}" fill="#FFFFFF" font-size="10" font-weight="700">Entry fill</text>
    <text x="${exit.x + 9}" y="${Math.max(plotTop + 12, exit.y - 11)}" fill="#FFFFFF" font-size="10" font-weight="700">Exit fill</text>
    <rect x="${partialLabelX}" y="${plotBottom - 23}" width="182" height="16" rx="3" fill="#10212a" stroke="${COLORS.partial}"/>
    <text x="${partialLabelX + 6}" y="${plotBottom - 11}" fill="${COLORS.dim}" font-size="9">5m partial at exit; no candle</text>
  </g>`;
  const closingSvg = presentation.lastIndexOf("</svg>");
  return closingSvg >= 0 ? presentation.slice(0, closingSvg) + overlay + presentation.slice(closingSvg) : presentation;
}

/** Read only a filename persisted by this module; no user-derived file path is accepted. */
export function readDailyRangeClosedChartSnapshotSvg(
  directory: string,
  snapshot: DailyRangeClosedChartSnapshot | null | undefined,
  trade?: DailyRangeClosedChartSnapshotTrade,
): string | null {
  if (snapshot?.status !== "CAPTURED" || snapshot.mimeType !== "image/svg+xml" || !snapshot.assetFile) return null;
  const root = resolve(directory);
  if (!/^[a-z0-9-]{4,64}\.svg$/i.test(snapshot.assetFile)) return null;
  const file = resolve(root, snapshot.assetFile);
  if (!file.startsWith(root + sep)) return null;
  try {
    // Old assets remain immutable on disk. Normalize only the presentation of
    // their execution dots while serving them, so historical reports match
    // the current white entry/exit-marker convention without rewriting data.
    const rendered = readFileSync(file, "utf8")
      .replace(/(<circle\b[^>]*\br="5"\s+fill=")(?:#f8fafc|#c4b5fd)(?="\s+stroke="#071016"\s+stroke-width="2"\/>)/gi, `$1${EXECUTION_MARKER_POINT_COLOR}`)
      .replace(/(<circle\b[^>]*\br="3"\s+fill=")(?:#f8fafc|#c4b5fd)(?="\/>)/gi, `$1${EXECUTION_MARKER_POINT_COLOR}`);
    return upgradeLegacyDailyRangeChartPresentation(rendered, trade);
  } catch {
    return null;
  }
}
