/**
 * PIT-safe feature extraction for the 36H market-direction model.
 *
 * WHY THIS IS THE ONLY IMPLEMENTATION
 * ----------------------------------
 * Train/serve skew is the classic way a model that backtests well trades badly: the training
 * matrix is built by one code path (usually Python/pandas) and inference by another (TypeScript),
 * and a single off-by-one in a rolling window silently changes what the model is fed in production.
 * This module is the SINGLE definition. The training matrix is generated by running THIS code over
 * historical bars (see scripts/build-direction-training-matrix.ts), so the features the model learns
 * are byte-identical to the features it is served. There is no second implementation to drift from.
 *
 * PIT SAFETY
 * ----------
 * Every function here reads bars with index <= `at` and never beyond. The caller passes the index of
 * the FORMATION bar; the label (forward 36h return) is attached only by the training script, never
 * here. `featuresAt` returns null rather than a partial vector when history is short — a partially
 * populated vector with zero-filled holes is indistinguishable from a real reading and would be
 * learned as signal.
 *
 * NULL DISCIPLINE
 * ---------------
 * Individual features may be null (a symbol lacking funding history, say). Nulls are preserved as
 * nulls through to the runtime, which converts them to the model's own missing-value sentinel. No
 * function here emits NaN — `safeDiv` and `finite` collapse every non-finite intermediate to null,
 * because NaN propagates silently through tree traversal and lands as a confident wrong prediction.
 */

export interface Bar {
  openTime: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  /** Taker buy base volume when available (Binance klines field 9). Null for sources without it. */
  takerBuyBase?: number | null;
}

export type FeatureVector = Record<string, number | null>;

/** Bars required before `featuresAt` will emit a vector: the longest lookback plus slack. */
export const DIRECTION_MODEL_MIN_BARS = 200;

/** Forward horizon the model predicts, in 1h bars. */
export const DIRECTION_MODEL_HORIZON_BARS = 36;

const finite = (x: number | null | undefined): number | null =>
  typeof x === "number" && Number.isFinite(x) ? x : null;

const safeDiv = (a: number | null, b: number | null): number | null => {
  if (a === null || b === null || b === 0) return null;
  return finite(a / b);
};

const pctChange = (now: number | null, then: number | null): number | null => {
  if (now === null || then === null || then <= 0) return null;
  return finite(now / then - 1);
};

const mean = (xs: number[]): number | null => {
  const v = xs.filter((x) => Number.isFinite(x));
  if (!v.length) return null;
  return finite(v.reduce((a, b) => a + b, 0) / v.length);
};

const median = (xs: number[]): number | null => {
  const v = xs.filter((x) => Number.isFinite(x)).sort((a, b) => a - b);
  if (!v.length) return null;
  const m = Math.floor(v.length / 2);
  return finite(v.length % 2 ? v[m] : (v[m - 1] + v[m]) / 2);
};

const stdev = (xs: number[]): number | null => {
  const v = xs.filter((x) => Number.isFinite(x));
  if (v.length < 2) return null;
  const m = v.reduce((a, b) => a + b, 0) / v.length;
  const varr = v.reduce((a, b) => a + (b - m) * (b - m), 0) / v.length;
  return finite(Math.sqrt(varr));
};

/** Ordinary-least-squares slope of close over the last `n` bars, normalised by price level so it is
 *  comparable across symbols of wildly different nominal price (PEPE vs BNB). */
function trendSlope(bars: Bar[], at: number, n: number): number | null {
  if (at + 1 < n) return null;
  const ys: number[] = [];
  for (let i = at - n + 1; i <= at; i += 1) {
    const c = finite(bars[i]?.close);
    if (c === null || c <= 0) return null;
    ys.push(c);
  }
  const nn = ys.length;
  const xbar = (nn - 1) / 2;
  const ybar = ys.reduce((a, b) => a + b, 0) / nn;
  let num = 0;
  let den = 0;
  for (let i = 0; i < nn; i += 1) {
    num += (i - xbar) * (ys[i] - ybar);
    den += (i - xbar) * (i - xbar);
  }
  if (den === 0 || ybar <= 0) return null;
  return finite((num / den) / ybar);
}

/** Wilder-style ATR over `n` bars, expressed as a fraction of price. */
function atrPct(bars: Bar[], at: number, n: number): number | null {
  if (at + 1 < n + 1) return null;
  const trs: number[] = [];
  for (let i = at - n + 1; i <= at; i += 1) {
    const h = finite(bars[i]?.high);
    const l = finite(bars[i]?.low);
    const pc = finite(bars[i - 1]?.close);
    if (h === null || l === null || pc === null) return null;
    trs.push(Math.max(h - l, Math.abs(h - pc), Math.abs(l - pc)));
  }
  const a = mean(trs);
  const c = finite(bars[at]?.close);
  return safeDiv(a, c);
}

/** Realised volatility: stdev of log returns over `n` bars. */
function realisedVol(bars: Bar[], at: number, n: number): number | null {
  if (at + 1 < n + 1) return null;
  const rs: number[] = [];
  for (let i = at - n + 1; i <= at; i += 1) {
    const c = finite(bars[i]?.close);
    const p = finite(bars[i - 1]?.close);
    if (c === null || p === null || c <= 0 || p <= 0) return null;
    rs.push(Math.log(c / p));
  }
  return stdev(rs);
}

/** Exponential moving average of close at `at` over `n` bars. */
function ema(bars: Bar[], at: number, n: number): number | null {
  if (at + 1 < n) return null;
  const k = 2 / (n + 1);
  let acc: number | null = null;
  for (let i = Math.max(0, at - n * 3); i <= at; i += 1) {
    const c = finite(bars[i]?.close);
    if (c === null) return null;
    acc = acc === null ? c : c * k + acc * (1 - k);
  }
  return finite(acc);
}

/**
 * Deterministic swing-point detection: a bar is a swing high if its high is the maximum of the
 * `w` bars either side of it. Systematic, not hand-drawn — the spec explicitly requires
 * support/resistance to be derived, not manual.
 * Only bars fully inside the window ending at `at` are considered, so nothing looks forward.
 */
function swings(bars: Bar[], at: number, lookback: number, w: number): { highs: number[]; lows: number[] } {
  const highs: number[] = [];
  const lows: number[] = [];
  const start = Math.max(w, at - lookback + 1);
  // A swing at index i needs w confirmed bars AFTER it, so i can be at most at-w — that keeps the
  // detection causal: a swing is only recognised once the market has already moved past it.
  for (let i = start; i <= at - w; i += 1) {
    const h = finite(bars[i]?.high);
    const l = finite(bars[i]?.low);
    if (h === null || l === null) continue;
    let isHigh = true;
    let isLow = true;
    for (let j = i - w; j <= i + w; j += 1) {
      if (j === i) continue;
      const hj = finite(bars[j]?.high);
      const lj = finite(bars[j]?.low);
      if (hj === null || lj === null) { isHigh = false; isLow = false; break; }
      if (hj >= h) isHigh = false;
      if (lj <= l) isLow = false;
    }
    if (isHigh) highs.push(h);
    if (isLow) lows.push(l);
  }
  return { highs, lows };
}

/** Per-symbol feature block. Prefixed by the caller when merged into the market vector. */
export function symbolFeatures(bars: Bar[], at: number): FeatureVector | null {
  if (!Array.isArray(bars) || at < DIRECTION_MODEL_MIN_BARS - 1 || at >= bars.length) return null;
  const c = finite(bars[at]?.close);
  if (c === null || c <= 0) return null;

  const closeAt = (back: number): number | null => finite(bars[at - back]?.close);

  const mom3 = pctChange(c, closeAt(3));
  const mom6 = pctChange(c, closeAt(6));
  const mom12 = pctChange(c, closeAt(12));
  const mom24 = pctChange(c, closeAt(24));
  const mom36 = pctChange(c, closeAt(36));

  // Momentum persistence: how much of the 36h move was already in place 12h ago. ~1 means the move
  // is stale and flattening; >1 means it has since retraced; <1 means it is still accelerating.
  const mom36Prior = pctChange(closeAt(12), closeAt(48));
  const momPersistence = mom36 !== null && mom36Prior !== null && Math.abs(mom36) > 1e-9
    ? finite(mom36Prior / mom36)
    : null;
  // Decay: short-horizon momentum relative to long-horizon. Positive = re-accelerating.
  const momDecay = mom12 !== null && mom36 !== null ? finite(mom12 - mom36 / 3) : null;

  const slope1h = trendSlope(bars, at, 12);
  const slope4h = trendSlope(bars, at, 48);

  // --- price structure -------------------------------------------------------------------
  const { highs, lows } = swings(bars, at, 120, 3);
  const lastHigh = highs.length ? highs[highs.length - 1] : null;
  const prevHigh = highs.length > 1 ? highs[highs.length - 2] : null;
  const lastLow = lows.length ? lows[lows.length - 1] : null;
  const prevLow = lows.length > 1 ? lows[lows.length - 2] : null;

  const hh = lastHigh !== null && prevHigh !== null ? (lastHigh > prevHigh ? 1 : 0) : null;
  const hl = lastLow !== null && prevLow !== null ? (lastLow > prevLow ? 1 : 0) : null;
  const lh = lastHigh !== null && prevHigh !== null ? (lastHigh < prevHigh ? 1 : 0) : null;
  const ll = lastLow !== null && prevLow !== null ? (lastLow < prevLow ? 1 : 0) : null;

  // Nearest structural resistance ABOVE and support BELOW current price.
  const resistance = highs.filter((h) => h > c).sort((a, b) => a - b)[0] ?? null;
  const support = lows.filter((l) => l < c).sort((a, b) => b - a)[0] ?? null;
  const distResistance = resistance !== null ? finite((resistance - c) / c) : null;
  const distSupport = support !== null ? finite((c - support) / c) : null;

  // Range position over the trailing 96h: 0 = at the low, 1 = at the high.
  let hi96 = -Infinity;
  let lo96 = Infinity;
  for (let i = Math.max(0, at - 95); i <= at; i += 1) {
    const h = finite(bars[i]?.high);
    const l = finite(bars[i]?.low);
    if (h === null || l === null) { hi96 = -Infinity; break; }
    hi96 = Math.max(hi96, h);
    lo96 = Math.min(lo96, l);
  }
  const rangePos = Number.isFinite(hi96) && hi96 > lo96 ? finite((c - lo96) / (hi96 - lo96)) : null;

  // Breakout: closed above the prior swing high this bar. Failed breakout: traded above it
  // intrabar but closed back below — the exhaustion signature the spec calls out explicitly.
  const priorHigh = lastHigh;
  const barHigh = finite(bars[at]?.high);
  const barLow = finite(bars[at]?.low);
  const breakout = priorHigh !== null ? (c > priorHigh ? 1 : 0) : null;
  const failedBreakout = priorHigh !== null && barHigh !== null
    ? (barHigh > priorHigh && c <= priorHigh ? 1 : 0)
    : null;
  const priorLow = lastLow;
  const breakdown = priorLow !== null ? (c < priorLow ? 1 : 0) : null;
  const failedBreakdown = priorLow !== null && barLow !== null
    ? (barLow < priorLow && c >= priorLow ? 1 : 0)
    : null;
  // Retest: price is within 0.5 ATR of the level it recently broke.
  const atr14 = atrPct(bars, at, 14);
  const retest = priorHigh !== null && atr14 !== null && atr14 > 0
    ? (Math.abs(c - priorHigh) / c < 0.5 * atr14 ? 1 : 0)
    : null;

  // --- volatility / exhaustion ------------------------------------------------------------
  const rv24 = realisedVol(bars, at, 24);
  const rv72 = realisedVol(bars, at, 72);
  const rangeExpansion = safeDiv(rv24, rv72);
  const ema24 = ema(bars, at, 24);
  const emaExtension = ema24 !== null && ema24 > 0 ? finite((c - ema24) / ema24) : null;
  const emaExtensionVol = emaExtension !== null && rv24 !== null && rv24 > 0
    ? finite(emaExtension / rv24)
    : null;

  // Jump: this bar's absolute return in units of ATR.
  const prevClose = closeAt(1);
  const barRet = pctChange(c, prevClose);
  const jump = barRet !== null && atr14 !== null && atr14 > 0 ? finite(Math.abs(barRet) / atr14) : null;

  // Wick/rejection: upper and lower shadow as a fraction of the bar's full range.
  const o = finite(bars[at]?.open);
  let upperWick: number | null = null;
  let lowerWick: number | null = null;
  if (o !== null && barHigh !== null && barLow !== null && barHigh > barLow) {
    const body = Math.abs(c - o);
    const range = barHigh - barLow;
    upperWick = finite((barHigh - Math.max(c, o)) / range);
    lowerWick = finite((Math.min(c, o) - barLow) / range);
    void body;
  }

  // --- volume / flow ----------------------------------------------------------------------
  const vols: number[] = [];
  for (let i = Math.max(0, at - 71); i <= at; i += 1) {
    const v = finite(bars[i]?.volume);
    if (v === null) { vols.length = 0; break; }
    vols.push(v);
  }
  const vNow = finite(bars[at]?.volume);
  const vMean = vols.length ? mean(vols.slice(0, -1)) : null;
  const vStd = vols.length ? stdev(vols.slice(0, -1)) : null;
  const volumeSurprise = vNow !== null && vMean !== null && vStd !== null && vStd > 0
    ? finite((vNow - vMean) / vStd)
    : null;
  const volumeRatio = safeDiv(vNow, vMean);
  const volumeClimax = volumeSurprise !== null ? (volumeSurprise > 2 ? 1 : 0) : null;

  /**
   * Taker buy/sell imbalance over a trailing window: (buy - sell) / total, in [-1, 1].
   * Returns null — never 0 — when any bar in the window lacks a taker split, because "no data"
   * and "perfectly balanced flow" are opposite readings and the model must be able to tell them
   * apart via its own missing-value routing.
   */
  const takerImbalanceOver = (n: number): number | null => {
    let buy = 0;
    let total = 0;
    for (let i = Math.max(0, at - (n - 1)); i <= at; i += 1) {
      const tb = finite(bars[i]?.takerBuyBase ?? null);
      const v = finite(bars[i]?.volume);
      if (tb === null || v === null) return null;
      buy += tb;
      total += v;
    }
    return total > 0 ? finite((2 * buy - total) / total) : null;
  };
  const takerImb1 = takerImbalanceOver(1);
  const takerImb4 = takerImbalanceOver(4);
  const takerImb12 = takerImbalanceOver(12);
  const takerImbalance = takerImbalanceOver(24);
  // Acceleration: is recent flow leaning harder than the day's baseline?
  const takerAccel = takerImb4 !== null && takerImbalance !== null ? finite(takerImb4 - takerImbalance) : null;
  // Persistence: how consistently one side has taken over the last 12 bars, in [0, 1].
  let takerPersistence: number | null = null;
  {
    let agree = 0;
    let seen = 0;
    let ok = true;
    for (let i = Math.max(0, at - 11); i <= at; i += 1) {
      const tb = finite(bars[i]?.takerBuyBase ?? null);
      const v = finite(bars[i]?.volume);
      if (tb === null || v === null) { ok = false; break; }
      if (v > 0) {
        seen += 1;
        if (2 * tb > v) agree += 1;
      }
    }
    if (ok && seen > 0) {
      // 0.5 = no persistence; 1 or 0 = one side took every bar. Folded to [0,1] as |2p-1|.
      takerPersistence = finite(Math.abs(2 * (agree / seen) - 1));
    }
  }

  // Momentum relationships the fast/slow split actually cares about.
  const mom3over12 = mom3 !== null && mom12 !== null ? finite(mom3 - mom12 / 4) : null;
  const mom6over24 = mom6 !== null && mom24 !== null ? finite(mom6 - mom24 / 4) : null;
  // Trend age: bars since the last sign flip of 12h momentum, capped at the lookback.
  let trendAge: number | null = null;
  {
    const sgn = (x: number | null): number | null => (x === null ? null : x > 0 ? 1 : x < 0 ? -1 : 0);
    const nowSign = sgn(mom12);
    if (nowSign !== null && at >= 60) {
      let age = 0;
      for (let back = 1; back <= 48; back += 1) {
        const m = pctChange(closeAt(back), closeAt(back + 12));
        if (sgn(m) !== nowSign) break;
        age += 1;
      }
      trendAge = age;
    }
  }

  return {
    mom3, mom6, mom12, mom24, mom36,
    momPersistence, momDecay, slope1h, slope4h,
    hh, hl, lh, ll,
    breakout, failedBreakout, breakdown, failedBreakdown, retest,
    distSupport, distResistance, rangePos,
    atr14, rv24, rv72, rangeExpansion,
    emaExtension, emaExtensionVol, jump, upperWick, lowerWick,
    volumeSurprise, volumeRatio, volumeClimax,
    takerImbalance, takerImb1, takerImb4, takerImb12, takerAccel, takerPersistence,
    mom3over12, mom6over24, trendAge,
  };
}

/** Names of the per-symbol block, used to build the aggregate schema deterministically. */
const SYMBOL_FEATURE_KEYS = [
  "mom3", "mom6", "mom12", "mom24", "mom36",
  "momPersistence", "momDecay", "slope1h", "slope4h",
  "hh", "hl", "lh", "ll",
  "breakout", "failedBreakout", "breakdown", "failedBreakdown", "retest",
  "distSupport", "distResistance", "rangePos",
  "atr14", "rv24", "rv72", "rangeExpansion",
  "emaExtension", "emaExtensionVol", "jump", "upperWick", "lowerWick",
  "volumeSurprise", "volumeRatio", "volumeClimax",
  "takerImbalance", "takerImb1", "takerImb4", "takerImb12", "takerAccel", "takerPersistence",
  "mom3over12", "mom6over24", "trendAge",
] as const;

/** Cross-sectional aggregate of a per-symbol feature across the universe. */
function crossAgg(perSymbol: FeatureVector[], key: string): { med: number | null; disp: number | null } {
  const vals = perSymbol.map((f) => f[key]).filter((v): v is number => v !== null && Number.isFinite(v));
  return { med: median(vals), disp: stdev(vals) };
}

/** One funding settlement. Intervals differ per symbol (8h is common, some are 4h), so features
 *  are always derived by "most recent settlement at or before the bar", never by a fixed stride. */
export interface FundingPoint {
  timeMs: number;
  rate: number;
}

export interface MarketFeatureInput {
  /** Bars per universe symbol, ascending by openTime, all aligned to the same grid. */
  bySymbol: Map<string, Bar[]>;
  /** BTC bars as the common market factor. May be absent; BTC features then read null. */
  btc: Bar[] | null;
  /** Index into every series identifying the FORMATION bar. Must be identical across symbols. */
  at: number;
  /** Funding history per symbol, ascending by time. Absent -> funding features read null. */
  fundingBySymbol?: Map<string, FundingPoint[]> | null;
  /** Cross-venue bars, implied-vol series and ETH. Every field is optional: a source that is down
   *  contributes nulls and a `src_available_*` flag of 0, never a thrown error and never a zero
   *  that the model would read as a real observation. */
  multiSource?: MultiSourceInput | null;
}

/**
 * PIT funding features for one symbol at wall-clock time `atMs`.
 *
 * Only settlements STRICTLY at or before `atMs` are visible. Binary search rather than a scan
 * because this runs once per symbol per row over ~17k rows.
 */
export function fundingFeatures(points: FundingPoint[] | undefined, atMs: number): {
  rate: number | null;
  change: number | null;
  z: number | null;
} {
  if (!points || !points.length) return { rate: null, change: null, z: null };
  let lo = 0;
  let hi = points.length - 1;
  let idx = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (points[mid]!.timeMs <= atMs) { idx = mid; lo = mid + 1; } else { hi = mid - 1; }
  }
  if (idx < 0) return { rate: null, change: null, z: null };
  const rate = finite(points[idx]!.rate);
  const prev = idx > 0 ? finite(points[idx - 1]!.rate) : null;
  const change = rate !== null && prev !== null ? finite(rate - prev) : null;
  // Normalise against this symbol's own recent funding regime rather than an absolute level:
  // a 0.01% rate means something different on a perpetually-positive-carry name than on a flat one.
  const windowStart = Math.max(0, idx - 89);
  const hist = points.slice(windowStart, idx + 1).map((p) => p.rate).filter((r) => Number.isFinite(r));
  const m = mean(hist);
  const sd = stdev(hist);
  const z = rate !== null && m !== null && sd !== null && sd > 0 ? finite((rate - m) / sd) : null;
  return { rate, change, z };
}

/**
 * The market-level feature vector the 36H model consumes.
 *
 * Target convention (fixed before any result was seen, per the spec's "jangan mengubah target
 * setelah melihat hasil"): the model predicts the MEDIAN forward 36h return of the active universe.
 * Median over equal-weight mean because a single 40% altcoin candle otherwise defines the label,
 * and the basket the prediction steers holds at most 6 of ~20 names.
 */
export function marketFeatures(input: MarketFeatureInput): FeatureVector | null {
  const { bySymbol, btc, at, fundingBySymbol } = input;
  const perSymbol: FeatureVector[] = [];
  for (const [, bars] of bySymbol) {
    const f = symbolFeatures(bars, at);
    if (f) perSymbol.push(f);
  }
  // A market reading built from a handful of surviving symbols is not the same statistic as one
  // built from the full universe; refuse rather than emit a thin vector that looks identical.
  if (perSymbol.length < 8) return null;

  const out: FeatureVector = {};
  for (const key of SYMBOL_FEATURE_KEYS) {
    const { med, disp } = crossAgg(perSymbol, key);
    out[`xs_med_${key}`] = med;
    out[`xs_disp_${key}`] = disp;
  }

  // Breadth family — the spec's cross-sectional market state block.
  const mom36s = perSymbol.map((f) => f.mom36).filter((v): v is number => v !== null);
  const mom12s = perSymbol.map((f) => f.mom12).filter((v): v is number => v !== null);
  out.xs_breadth_mom36 = mom36s.length ? finite(mom36s.filter((v) => v > 0).length / mom36s.length) : null;
  out.xs_breadth_mom12 = mom12s.length ? finite(mom12s.filter((v) => v > 0).length / mom12s.length) : null;
  const sorted36 = [...mom36s].sort((a, b) => b - a);
  const top3 = sorted36.slice(0, 3);
  const bot3 = sorted36.slice(-3);
  const topMean = mean(top3);
  const botMean = mean(bot3);
  out.xs_top_bottom_spread = topMean !== null && botMean !== null ? finite(topMean - botMean) : null;
  out.xs_top3_mom36 = topMean;
  out.xs_bottom3_mom36 = botMean;
  out.xs_universe_n = perSymbol.length;

  // Funding block: the cross-section of carry, aggregated the same way as every other family.
  // Median rather than mean so one extreme-funding altcoin cannot define the market reading.
  {
    const anyBars = [...bySymbol.values()][0];
    const atMs = anyBars?.[at]?.openTime ?? null;
    const rates: number[] = [];
    const changes: number[] = [];
    const zs: number[] = [];
    if (atMs !== null && fundingBySymbol) {
      for (const sym of bySymbol.keys()) {
        const f = fundingFeatures(fundingBySymbol.get(sym), atMs);
        if (f.rate !== null) rates.push(f.rate);
        if (f.change !== null) changes.push(f.change);
        if (f.z !== null) zs.push(f.z);
      }
    }
    out.xs_funding_median = rates.length ? median(rates) : null;
    out.xs_funding_change_median = changes.length ? median(changes) : null;
    out.xs_funding_z_median = zs.length ? median(zs) : null;
    out.xs_funding_disp = rates.length > 1 ? stdev(rates) : null;
    // Share of the universe paying longs (negative funding) — a crowding read, not a level read.
    out.xs_funding_negative_share = rates.length
      ? finite(rates.filter((r) => r < 0).length / rates.length)
      : null;
  }

  // BTC / common factor block.
  const btcF = btc ? symbolFeatures(btc, at) : null;
  out.btc_mom12 = btcF?.mom12 ?? null;
  out.btc_mom24 = btcF?.mom24 ?? null;
  out.btc_mom36 = btcF?.mom36 ?? null;
  out.btc_slope4h = btcF?.slope4h ?? null;
  out.btc_rv24 = btcF?.rv24 ?? null;
  out.btc_rangePos = btcF?.rangePos ?? null;
  out.btc_emaExtensionVol = btcF?.emaExtensionVol ?? null;
  out.btc_breakout = btcF?.breakout ?? null;
  out.btc_failedBreakout = btcF?.failedBreakout ?? null;
  out.btc_takerImbalance = btcF?.takerImbalance ?? null;
  out.btc_mom3 = btcF?.mom3 ?? null;
  out.btc_mom6 = btcF?.mom6 ?? null;
  out.btc_atr14 = btcF?.atr14 ?? null;
  out.btc_rangeExpansion = btcF?.rangeExpansion ?? null;
  out.btc_hh = btcF?.hh ?? null;
  out.btc_ll = btcF?.ll ?? null;
  out.btc_trendAge = btcF?.trendAge ?? null;

  // Breadth acceleration: is participation broadening or narrowing? Positive means the short
  // horizon is more broadly positive than the long one, i.e. fresh names are joining.
  const b3 = out.xs_breadth_mom36;
  const b12 = out.xs_breadth_mom12;
  out.xs_breadth_accel = b3 !== null && b12 !== null ? finite(b12 - b3) : null;

  // ETH as a second common-factor leg, and BTC/ETH disagreement — when the two majors part company
  // the alt complex usually has no clean common direction to follow.
  const ethF = input.multiSource?.eth ? symbolFeatures(input.multiSource.eth, at) : null;
  out.eth_mom6 = ethF?.mom6 ?? null;
  out.eth_mom12 = ethF?.mom12 ?? null;
  out.eth_mom24 = ethF?.mom24 ?? null;
  out.eth_mom36 = ethF?.mom36 ?? null;
  out.eth_rv24 = ethF?.rv24 ?? null;
  out.eth_rangePos = ethF?.rangePos ?? null;
  const bm = out.btc_mom12;
  const em = out.eth_mom12;
  out.majors_disagreement = bm !== null && em !== null ? finite(bm - em) : null;
  // Alt complex versus the majors: is the median name leading or lagging BTC?
  const medMom12 = out.xs_med_mom12;
  out.alt_vs_btc = medMom12 !== null && bm !== null ? finite(medMom12 - bm) : null;

  // Cross-venue and options block, read strictly as-of the formation instant.
  const anyBarsForMs = [...bySymbol.values()][0];
  const atMsForSources = anyBarsForMs?.[at]?.openTime ?? null;
  if (atMsForSources !== null) {
    const ref = {
      ret1h: pctChange(finite(anyBarsForMs![at]!.close), finite(anyBarsForMs![at - 1]?.close ?? null)),
      ret12h: out.xs_med_mom12,
    };
    Object.assign(out, multiSourceFeatures(input.multiSource, atMsForSources, ref));
  }

  return out;
}

/**
 * Stable, sorted feature-name schema. The artifact records the exact order it was trained on and
 * the runtime asserts against it, so a feature added here can never silently shift the vector the
 * model reads (a reordering is the quietest possible way to corrupt every prediction).
 */
export function featureNames(sample: FeatureVector): string[] {
  return Object.keys(sample).sort();
}

/** The label the training script attaches: median forward 36h return of the universe. */
export function forwardMedianReturn(bySymbol: Map<string, Bar[]>, at: number, horizonBars: number): number | null {
  const rets: number[] = [];
  for (const [, bars] of bySymbol) {
    const now = finite(bars[at]?.close);
    const fwd = finite(bars[at + horizonBars]?.close);
    if (now === null || fwd === null || now <= 0) continue;
    rets.push(fwd / now - 1);
  }
  if (rets.length < 8) return null;
  return median(rets);
}

// ---------------------------------------------------------------------------------------------
// V2 TARGET DEFINITION
// ---------------------------------------------------------------------------------------------
//
// The allocation this model steers is, in substance, a choice of how much COMMON-MARKET BETA the
// basket carries. So the label must be the common move of the pool the basket actually draws from —
// not one coin, and not a broad index containing names the basket can never hold.
//
// TARGET (fixed before any result was inspected):
//
//   R36_market = MEDIAN over the PIT-active universe of (close[t+36] / close[t] - 1)
//
// Median, not equal-weight mean: the basket holds at most 6 of ~20 names, and a single altcoin
// printing +40% would otherwise define the label for an hour when the pool as a whole did nothing.
// The median is the return of the typical name, which is what a 6-leg slice is exposed to.
//
//   VOL36 = PIT volatility of that same common factor, scaled to the 36h horizon
//
// Computed ONLY from bars at or before t: the per-bar cross-sectional median return series is built
// backwards from t, its stdev taken over a trailing window, then scaled by sqrt(36). Using realised
// forward volatility here would leak the answer into the question.
//
//   Z36 = R36_market / VOL36
//
// Normalising is the point of V2. A +0.4% common move is a strong directional signal in a quiet
// tape and noise in a violent one; an un-normalised binary label calls both "UP" and teaches the
// model to chase whichever regime happened to be calmer. Z36 asks the question the allocation
// actually needs answered: is the next 36h move LARGE RELATIVE TO ITS OWN NOISE?

/** Trailing window (bars) used to estimate common-factor volatility. 14 days of hourly bars. */
export const VOL_LOOKBACK_BARS = 336;

export type DirectionClass = "STRONG_UP" | "NEUTRAL" | "STRONG_DOWN";

/** Default |Z| boundary separating a directional move from noise. Frozen, not tuned per-sample. */
export const Z_CLASS_BOUNDARY = 0.5;

/** Per-bar cross-sectional median return of the universe, for bar index `i` (uses i-1 and i only). */
function commonBarReturn(bySymbol: Map<string, Bar[]>, i: number): number | null {
  const rets: number[] = [];
  for (const [, bars] of bySymbol) {
    const now = finite(bars[i]?.close);
    const prev = finite(bars[i - 1]?.close);
    if (now === null || prev === null || prev <= 0) continue;
    rets.push(now / prev - 1);
  }
  return rets.length >= 8 ? median(rets) : null;
}

/**
 * PIT expected volatility of the common factor over the forward horizon.
 * Strictly backward-looking: only bars with index <= `at` are read.
 */
export function commonForwardVol(
  bySymbol: Map<string, Bar[]>,
  at: number,
  horizonBars: number,
  lookback: number = VOL_LOOKBACK_BARS,
): number | null {
  const rs: number[] = [];
  for (let i = Math.max(1, at - lookback + 1); i <= at; i += 1) {
    const r = commonBarReturn(bySymbol, i);
    if (r !== null) rs.push(r);
  }
  // Require most of the window: a volatility estimate from a handful of bars is not a scale, and
  // dividing by it would manufacture enormous |Z| values out of thin data.
  if (rs.length < lookback * 0.5) return null;
  const sd = stdev(rs);
  return sd === null || sd <= 0 ? null : finite(sd * Math.sqrt(horizonBars));
}

/** The V2 label: common-market forward return, its PIT vol scale, the normalised Z, and the class. */
export function v2Label(
  bySymbol: Map<string, Bar[]>,
  at: number,
  horizonBars: number,
  boundary: number = Z_CLASS_BOUNDARY,
): { r36: number; vol36: number; z36: number; cls: DirectionClass } | null {
  const r36 = forwardMedianReturn(bySymbol, at, horizonBars);
  if (r36 === null) return null;
  const vol36 = commonForwardVol(bySymbol, at, horizonBars);
  if (vol36 === null) return null;
  const z36 = r36 / vol36;
  if (!Number.isFinite(z36)) return null;
  const cls: DirectionClass = z36 >= boundary ? "STRONG_UP" : z36 <= -boundary ? "STRONG_DOWN" : "NEUTRAL";
  return { r36, vol36, z36, cls };
}

// ---------------------------------------------------------------------------------------------
// MULTI-HORIZON TARGETS
// ---------------------------------------------------------------------------------------------
//
// One 36h label cannot distinguish "6/12/24/36 all bullish" from "6/12 bearish, 24/36 bullish".
// Those are different states and deserve different conviction, so each horizon gets its own
// volatility-normalised 3-class label and the meta model learns how their agreement maps onto the
// final 36h distribution. Every horizon uses the SAME normalisation philosophy: the vol scale is
// estimated strictly backwards and rescaled by sqrt(h), so Z is comparable across horizons.

export const HORIZONS = [6, 12, 24, 36] as const;
export type Horizon = (typeof HORIZONS)[number];

export interface HorizonLabel {
  r: number;
  vol: number;
  z: number;
  cls: DirectionClass;
}

/** Labels for every horizon at one formation index, or null if any horizon cannot be formed. */
export function multiHorizonLabels(
  bySymbol: Map<string, Bar[]>,
  at: number,
  boundary: number = Z_CLASS_BOUNDARY,
): Record<Horizon, HorizonLabel> | null {
  const out = {} as Record<Horizon, HorizonLabel>;
  for (const h of HORIZONS) {
    const r = forwardMedianReturn(bySymbol, at, h);
    if (r === null) return null;
    const vol = commonForwardVol(bySymbol, at, h);
    if (vol === null) return null;
    const z = r / vol;
    if (!Number.isFinite(z)) return null;
    out[h] = { r, vol, z, cls: z >= boundary ? "STRONG_UP" : z <= -boundary ? "STRONG_DOWN" : "NEUTRAL" };
  }
  return out;
}

// ---------------------------------------------------------------------------------------------
// MULTI-SOURCE FEATURES
// ---------------------------------------------------------------------------------------------

/** A timestamped external series (implied vol, venue price, OI, ...). Ascending by timeMs. */
export interface TimePoint {
  timeMs: number;
  value: number;
}

/**
 * Most recent value at or before `atMs`. Binary search; returns null when the series starts later.
 *
 * This is the ONLY way external sources are read. Independent feeds publish on their own cadences
 * and with their own gaps, so aligning them by array position silently mixes timestamps — a defect
 * this system has already paid for once on testnet. Everything here is "latest observation not
 * after the formation instant", which is also exactly the PIT rule.
 */
export function asOf(series: TimePoint[] | undefined | null, atMs: number, maxAgeMs?: number): number | null {
  if (!series || !series.length) return null;
  let lo = 0;
  let hi = series.length - 1;
  let idx = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (series[mid]!.timeMs <= atMs) { idx = mid; lo = mid + 1; } else { hi = mid - 1; }
  }
  if (idx < 0) return null;
  // A source-specific staleness bound: an OI reading from three days ago is not "current OI", and
  // serving it as one would look like real data rather than a gap.
  if (maxAgeMs !== undefined && atMs - series[idx]!.timeMs > maxAgeMs) return null;
  return finite(series[idx]!.value);
}

/** Bars indexed by openTime, so a venue series can be read at an exact instant. */
export function indexBars(bars: Bar[]): Map<number, Bar> {
  const m = new Map<number, Bar>();
  for (const b of bars) m.set(b.openTime, b);
  return m;
}

/**
 * Most recent venue bar at or before `atMs`, within `maxAgeMs`.
 *
 * NOT an exact-timestamp lookup. Independent venues close their bars on their own schedules and a
 * collector is always at least one bar behind the exchange it polls; requiring an exact match made
 * every venue feature null in production even though the store was only ~1h stale. As-of with an
 * explicit freshness bound is the same rule every other external source here uses, and it still
 * cannot read anything published after the formation instant.
 */
function venueAsOf(byTime: Map<number, Bar>, atMs: number, maxAgeMs: number): Bar | null {
  const exact = byTime.get(atMs);
  if (exact) return exact;
  let best: Bar | null = null;
  for (const [t, b] of byTime) {
    if (t > atMs) continue;
    if (atMs - t > maxAgeMs) continue;
    if (!best || t > best.openTime) best = b;
  }
  return best;
}

export interface MultiSourceInput {
  /** venue -> symbol -> openTime-indexed bars. Venue absence is normal and must not throw. */
  venueBars?: Map<string, Map<string, Map<number, Bar>>> | null;
  /** currency -> implied-volatility index series (Deribit DVOL). */
  ivSeries?: Map<string, TimePoint[]> | null;
  /** ETH bars for the second common-factor leg. */
  eth?: Bar[] | null;
}

const VENUE_NAMES = ["bybit", "okx", "coinbase"] as const;

/**
 * Cross-venue and options features.
 *
 * Cross-venue AGGRESSIVE flow is not in this block, and deliberately so: only Binance publishes a
 * taker split in its klines, so per-venue buy/sell pressure has no history on Bybit/OKX/Coinbase.
 * What those venues can honestly supply is agreement — did each venue's price move the same way,
 * how is volume distributed, how far do they diverge — and that is what is built. Claiming
 * per-venue aggression from a plain volume figure would be inventing data.
 */
export function multiSourceFeatures(
  ms: MultiSourceInput | null | undefined,
  atMs: number,
  binanceRef: { ret1h: number | null; ret12h: number | null } | null,
): FeatureVector {
  const out: FeatureVector = {};

  // ---- venue agreement -------------------------------------------------------------------
  const venueReturns: Array<{ venue: string; ret: number }> = [];
  const venueVols: Array<{ venue: string; vol: number }> = [];
  for (const venue of VENUE_NAMES) {
    const bySym = ms?.venueBars?.get(venue) ?? null;
    out[`src_available_${venue}`] = bySym ? 1 : 0;
    if (!bySym) continue;
    const rets: number[] = [];
    const vols: number[] = [];
    // Three hours of tolerance: enough to absorb a lagging collector or a venue that publishes late,
    // far short of letting a genuinely dead feed masquerade as current.
    const VENUE_MAX_AGE = 3 * 3_600_000;
    for (const [, byTime] of bySym) {
      const now = venueAsOf(byTime, atMs, VENUE_MAX_AGE);
      const prev = now ? venueAsOf(byTime, now.openTime - 3_600_000, VENUE_MAX_AGE) : null;
      if (!now || !prev || now.openTime === prev.openTime) continue;
      const c = finite(now.close);
      const p = finite(prev.close);
      if (c === null || p === null || p <= 0) continue;
      rets.push(c / p - 1);
      const v = finite(now.volume);
      if (v !== null) vols.push(v);
    }
    const m = median(rets);
    if (m !== null) venueReturns.push({ venue, ret: m });
    const mv = median(vols);
    if (mv !== null) venueVols.push({ venue, vol: mv });
  }

  const rets = venueReturns.map((v) => v.ret);
  out.xv_venue_count = venueReturns.length;
  out.xv_median_return = rets.length ? median(rets) : null;
  out.xv_return_dispersion = rets.length > 1 ? stdev(rets) : null;
  out.xv_bullish_count = rets.length ? rets.filter((r) => r > 0).length : null;
  out.xv_bearish_count = rets.length ? rets.filter((r) => r < 0).length : null;
  // Agreement ratio in [0,1]: 1 = every venue moved the same way, 0.5 = split.
  out.xv_agreement_ratio = rets.length
    ? finite(Math.max(rets.filter((r) => r > 0).length, rets.filter((r) => r < 0).length) / rets.length)
    : null;
  // Binance leading or lagging the rest is itself information: a move only Binance sees is weaker
  // evidence than the same move confirmed everywhere.
  const xvMed = out.xv_median_return;
  out.xv_binance_divergence = binanceRef?.ret1h !== null && binanceRef?.ret1h !== undefined && xvMed !== null
    ? finite(binanceRef.ret1h - xvMed)
    : null;

  // ---- options / implied volatility -------------------------------------------------------
  const IV_MAX_AGE = 6 * 3_600_000;
  for (const cur of ["BTC", "ETH"] as const) {
    const s = ms?.ivSeries?.get(cur) ?? null;
    const iv = asOf(s, atMs, IV_MAX_AGE);
    const iv24 = asOf(s, atMs - 24 * 3_600_000, IV_MAX_AGE);
    const iv72 = asOf(s, atMs - 72 * 3_600_000, IV_MAX_AGE);
    out[`opt_iv_${cur.toLowerCase()}`] = iv;
    out[`opt_iv_chg24_${cur.toLowerCase()}`] = iv !== null && iv24 !== null ? finite(iv - iv24) : null;
    out[`opt_iv_chg72_${cur.toLowerCase()}`] = iv !== null && iv72 !== null ? finite(iv - iv72) : null;
  }
  out.src_available_options = (ms?.ivSeries?.size ?? 0) > 0 ? 1 : 0;

  // ---- ETH as a second common factor ------------------------------------------------------
  out.src_available_eth = ms?.eth ? 1 : 0;

  return out;
}

// ---------------------------------------------------------------------------------------------
// V4 TRAJECTORY / PATH LABELS
// ---------------------------------------------------------------------------------------------
//
// WHY A PATH AND NOT AN ENDPOINT
// ------------------------------
// V3 asked "where is the market at +36h?" and flattened everything in between. Two very different
// futures collapse to the same answer under that question:
//
//     6h down, 12h down, 24h up, 36h up     a sell-off that bottoms and reverses
//     6h up,   12h up,   24h up, 36h up     a trend that simply persists
//
// Both can end at the same +36h level, and the measured consequence was visible in V3: the 6h
// specialist nearly matched its base rate while the 36h specialist was far worse than its own. The
// information decays into the endpoint. Labelling the SHAPE keeps it.
//
// Classes are deliberately few and interpretable. Every one of them has a distinct allocation
// consequence — that is the test for whether a class deserves to exist at all.

export type PathClass =
  | "PERSISTENT_UP"
  | "PERSISTENT_DOWN"
  | "UP_THEN_REVERSAL"
  | "DOWN_THEN_REVERSAL"
  | "EARLY_UP_THEN_FLAT"
  | "EARLY_DOWN_THEN_FLAT"
  | "CHOP"
  | "TRANSITION";

export const PATH_CLASSES: readonly PathClass[] = [
  "PERSISTENT_UP", "PERSISTENT_DOWN", "UP_THEN_REVERSAL", "DOWN_THEN_REVERSAL",
  "EARLY_UP_THEN_FLAT", "EARLY_DOWN_THEN_FLAT", "CHOP", "TRANSITION",
];

/**
 * Path class from the four volatility-normalised forward returns.
 *
 * Z is used rather than raw return for the same reason V2 adopted it: a +0.4% leg is decisive in a
 * quiet tape and noise in a violent one, and calling the quiet one a "reversal" would manufacture
 * path structure out of noise. Because vol_h scales by sqrt(h), Z is directly comparable across the
 * four horizons, which is what makes "early vs late" a meaningful comparison at all.
 *
 * `boundary` is the same frozen 0.5 the 3-class labels use — not tuned, and never fitted on holdout.
 */
export function pathClassFrom(
  z6: number, z12: number, z24: number, z36: number,
  boundary: number = Z_CLASS_BOUNDARY,
): PathClass {
  const sgn = (z: number): number => (z >= boundary ? 1 : z <= -boundary ? -1 : 0);
  const s6 = sgn(z6);
  const s12 = sgn(z12);
  const s24 = sgn(z24);
  const s36 = sgn(z36);

  const early = s6 + s12;   // -2..+2
  const late = s24 + s36;

  if (s6 > 0 && s12 > 0 && s24 > 0 && s36 > 0) return "PERSISTENT_UP";
  if (s6 < 0 && s12 < 0 && s24 < 0 && s36 < 0) return "PERSISTENT_DOWN";

  // A reversal needs BOTH halves to commit, in opposite directions. Requiring the full |2| on each
  // side keeps "one ambiguous leg" out of the reversal classes, which would otherwise absorb most
  // of the sample and make the class meaningless.
  if (early >= 1 && late <= -1) return "UP_THEN_REVERSAL";
  if (early <= -1 && late >= 1) return "DOWN_THEN_REVERSAL";

  if (early >= 1 && late === 0) return "EARLY_UP_THEN_FLAT";
  if (early <= -1 && late === 0) return "EARLY_DOWN_THEN_FLAT";

  if (s6 === 0 && s12 === 0 && s24 === 0 && s36 === 0) return "CHOP";
  return "TRANSITION";
}

/** Convenience: path class straight from the multi-horizon label bundle. */
export function pathClassFromLabels(
  labels: Record<Horizon, HorizonLabel>,
  boundary: number = Z_CLASS_BOUNDARY,
): PathClass {
  return pathClassFrom(labels[6].z, labels[12].z, labels[24].z, labels[36].z, boundary);
}
