/**
 * Immutable Daily Range close-chart artifact.
 *
 * This is deliberately an SVG generated by the execution process, not a
 * dashboard screenshot or a fresh public-chart query.  Every candle is capped
 * at the confirmed exchange exit timestamp, so reopening a closed report
 * cannot silently pull in later price action.
 */
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { resolve, sep } from "node:path";

import type { FuturesKline } from "./binance-futures-private.js";

export const DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION = "daily-range-closed-chart-svg-v2" as const;

export type DailyRangeClosedChartSnapshot = {
  version: typeof DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION;
  /** CAPTURED assets are immutable. PENDING means the close was safe but the visual feed failed. */
  status: "CAPTURED" | "PENDING" | "UNAVAILABLE";
  requestedAt: string;
  capturedAt: string | null;
  source: "BINANCE_USDM_COMPLETED_CANDLES";
  entryAt: string | null;
  exitAt: string | null;
  assetFile: string | null;
  mimeType: "image/svg+xml" | null;
  fiveMinuteCandleCount: number;
  fourHourCandleCount: number;
  reason: string | null;
};

type SnapshotDirection = "LONG" | "SHORT";
type SnapshotEntryPolicy = "LEGACY_CONTINUATION" | "CONTINUATION" | "FADE";

export type DailyRangeClosedChartSnapshotTrade = Readonly<{
  tradeId: string;
  symbol: string;
  direction: SnapshotDirection;
  entryPolicy?: SnapshotEntryPolicy;
  breakoutDirection?: "UP" | "DOWN" | null;
  entrySubmittedAt: string;
  entryFilledAt: string | null;
  entryFillPrice: number | null;
  exitTimestamp: string | null;
  exitPrice: number | null;
  rangeHigh: number;
  rangeLow: number;
  stopPrice: number | null;
  takeProfitPrice: number | null;
  rrTarget: number;
  referenceTimezone?: "UTC" | "America/New_York";
  referenceRangeOpenTime?: number | null;
  referenceRangeCloseTime?: number | null;
  confirmationBar1: SnapshotCandle;
  confirmationBar2: SnapshotCandle;
}>;

export type SnapshotCandle = Readonly<{
  openTime: number;
  closeTime: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}>;

export type DailyRangeClosedChartSnapshotClient = Pick<
  { getKlines(symbol: string, interval: "5m" | "4h", opts?: { startTime?: number; endTime?: number }): Promise<FuturesKline[]> },
  "getKlines"
>;

const FIVE_MINUTE_MS = 5 * 60_000;
const FOUR_HOURS_MS = 4 * 60 * 60_000;
const FIVE_MINUTE_EMA_CONTEXT_BARS = 50;
const FOUR_HOUR_CONTEXT_BARS = 96;

const COLORS = {
  background: "#071016",
  panel: "#0b171e",
  border: "#29414c",
  grid: "#263d48",
  text: "#dbe7ec",
  dim: "#8fa5ae",
  up: "#5ce4a6",
  down: "#ff777d",
  entry: "#f8fafc",
  exit: "#c4b5fd",
  stop: "#ff6b6b",
  takeProfit: "#46d39a",
  rangeHigh: "#6fb3d6",
  rangeLow: "#f0b54b",
  ema20: "#eedd88",
  ema50: "#aa4499",
  resistance: "#ff9f66",
  support: "#77b7ff",
} as const;

type OverlayPoint = { openTime: number; value: number };
type StructuralLine = { kind: "RESISTANCE" | "SUPPORT"; points: OverlayPoint[] };
type PriceLevel = { label: string; price: number; color: string; dash?: string };
type SnapshotMarker = {
  label: string;
  at: number;
  price: number;
  color: string;
  position: "above" | "below" | "middle";
  labelAnchor?: "start" | "end";
};
type RiskZone = { from: number; to: number; color: string; label: string };

function finite(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function positive(value: unknown): value is number {
  return finite(value) && value > 0;
}

function toMs(value: string | null | undefined): number | null {
  if (!value) return null;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function asSnapshotCandle(value: FuturesKline | SnapshotCandle): SnapshotCandle | null {
  if (!positive(value.openTime) || !positive(value.closeTime)
    || !positive(value.open) || !positive(value.high) || !positive(value.low) || !positive(value.close)
    || !finite(value.volume) || value.volume < 0) return null;
  return {
    openTime: value.openTime,
    closeTime: value.closeTime,
    open: value.open,
    high: value.high,
    low: value.low,
    close: value.close,
    volume: value.volume,
  };
}

function distinctCandles(rows: readonly (FuturesKline | SnapshotCandle)[], startMs: number, exitMs: number): SnapshotCandle[] {
  const unique = new Map<number, SnapshotCandle>();
  for (const row of rows) {
    const candle = asSnapshotCandle(row);
    // A partial candle that was still forming when the exit happened must never
    // appear in a "last chart at close" artifact.
    if (!candle || candle.openTime < startMs || candle.closeTime >= exitMs) continue;
    unique.set(candle.openTime, candle);
  }
  return [...unique.values()].sort((left, right) => left.openTime - right.openTime);
}

function escapeXml(value: string): string {
  return value.replace(/[<>&"']/g, (character) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "\"": "&quot;", "'": "&apos;" })[character]!);
}

function formatPrice(value: number): string {
  const digits = value < 0.0001 ? 10 : value < 0.01 ? 8 : value < 1 ? 6 : value < 100 ? 4 : 2;
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value);
}

function formatTaipei(ms: number): string {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: false,
    timeZone: "Asia/Taipei",
  }).format(new Date(ms)).replace(",", "");
}

function formatTaipeiShort(ms: number): string {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false,
    timeZone: "Asia/Taipei",
  }).format(new Date(ms)).replace(",", " ");
}

function calculateEma(candles: readonly SnapshotCandle[], period: number): OverlayPoint[] {
  if (candles.length < period) return [];
  const seed = candles.slice(0, period).reduce((sum, candle) => sum + candle.close, 0) / period;
  const multiplier = 2 / (period + 1);
  let value = seed;
  const points: OverlayPoint[] = [{ openTime: candles[period - 1]!.openTime, value }];
  for (let index = period; index < candles.length; index += 1) {
    value = (candles[index]!.close - value) * multiplier + value;
    points.push({ openTime: candles[index]!.openTime, value });
  }
  return points;
}

function latestStructuralLine(candles: readonly SnapshotCandle[], kind: StructuralLine["kind"]): StructuralLine | null {
  const pivots: OverlayPoint[] = [];
  const radius = 2;
  for (let index = radius; index < candles.length - radius; index += 1) {
    const candidate = candles[index]!;
    const candidateValue = kind === "RESISTANCE" ? candidate.high : candidate.low;
    let valid = true;
    for (let offset = 1; offset <= radius; offset += 1) {
      const before = candles[index - offset]!;
      const after = candles[index + offset]!;
      const beforeValue = kind === "RESISTANCE" ? before.high : before.low;
      const afterValue = kind === "RESISTANCE" ? after.high : after.low;
      if (kind === "RESISTANCE" ? candidateValue <= beforeValue || candidateValue <= afterValue : candidateValue >= beforeValue || candidateValue >= afterValue) {
        valid = false;
        break;
      }
    }
    if (valid) pivots.push({ openTime: candidate.openTime, value: candidateValue });
  }
  if (pivots.length < 2) return null;
  const first = pivots[pivots.length - 2]!;
  const second = pivots[pivots.length - 1]!;
  const elapsed = second.openTime - first.openTime;
  if (!(elapsed > 0)) return null;
  const latest = candles.at(-1)!;
  const slope = (second.value - first.value) / elapsed;
  const points = [first, second];
  if (latest.openTime > second.openTime) points.push({ openTime: latest.openTime, value: second.value + slope * (latest.openTime - second.openTime) });
  return { kind, points };
}

function linePoints(points: readonly OverlayPoint[], x: (value: number) => number, y: (value: number) => number, start: number, end: number): string {
  return points
    .filter((point) => point.openTime >= start && point.openTime <= end && finite(point.value))
    .map((point) => `${x(point.openTime).toFixed(2)},${y(point.value).toFixed(2)}`)
    .join(" ");
}

function candleAtOrNearest(candles: readonly SnapshotCandle[], at: number): SnapshotCandle | null {
  let selected: SnapshotCandle | null = null;
  let distance = Number.POSITIVE_INFINITY;
  for (const candle of candles) {
    const nextDistance = Math.abs(candle.openTime - at);
    if (nextDistance < distance) {
      selected = candle;
      distance = nextDistance;
    }
  }
  return selected;
}

function renderPanel(input: {
  x: number;
  y: number;
  width: number;
  height: number;
  title: string;
  subtitle: string;
  candles: SnapshotCandle[];
  allCandles: SnapshotCandle[];
  intervalMs: number;
  viewportStart: number;
  viewportEnd: number;
  levels: PriceLevel[];
  markers: SnapshotMarker[];
  zones?: RiskZone[];
  showStructure?: boolean;
}): string {
  const { x: outerX, y: outerY, width, height, title, subtitle, candles, allCandles, intervalMs, viewportStart, viewportEnd, levels, markers, zones = [], showStructure = false } = input;
  const left = outerX + 72;
  const right = outerX + width - 148;
  const top = outerY + 48;
  // Keep chart labels and the legend in their own footer space. Previously
  // both occupied the same band, which made the time axis unreadable.
  const bottom = outerY + height - 102;
  const plotWidth = Math.max(1, right - left);
  const plotHeight = Math.max(1, bottom - top);
  const timeStart = Math.min(viewportStart, viewportEnd - intervalMs);
  const timeEnd = Math.max(viewportEnd, timeStart + intervalMs);
  const visible = candles.filter((candle) => candle.openTime + intervalMs > timeStart && candle.openTime <= timeEnd);
  const ema20 = calculateEma(allCandles, 20);
  const ema50 = calculateEma(allCandles, 50);
  const resistance = showStructure ? latestStructuralLine(allCandles, "RESISTANCE") : null;
  const support = showStructure ? latestStructuralLine(allCandles, "SUPPORT") : null;
  const values = [
    ...visible.flatMap((candle) => [candle.high, candle.low]),
    ...levels.map((level) => level.price),
    ...ema20.filter((point) => point.openTime >= timeStart && point.openTime <= timeEnd).map((point) => point.value),
    ...ema50.filter((point) => point.openTime >= timeStart && point.openTime <= timeEnd).map((point) => point.value),
    ...(resistance?.points ?? []).map((point) => point.value),
    ...(support?.points ?? []).map((point) => point.value),
  ].filter(positive);
  const minimum = values.length ? Math.min(...values) : 0;
  const maximum = values.length ? Math.max(...values) : 1;
  const padding = Math.max((maximum - minimum) * 0.1, maximum * 0.001, 1e-10);
  const low = minimum - padding;
  const high = maximum + padding;
  const x = (at: number): number => left + (at - timeStart) / (timeEnd - timeStart) * plotWidth;
  const y = (price: number): number => top + (high - price) / (high - low) * plotHeight;
  const clipId = `clip-${Math.round(outerX)}-${Math.round(outerY)}`;
  const horizontalGrid = Array.from({ length: 5 }, (_, index) => {
    const ratio = index / 4;
    const price = high - ratio * (high - low);
    const yy = top + ratio * plotHeight;
    return `<line x1="${left}" y1="${yy}" x2="${right}" y2="${yy}" stroke="${COLORS.grid}" stroke-width="1" opacity="0.72"/><text x="${right + 10}" y="${yy + 4}" fill="${COLORS.dim}" font-size="13">${escapeXml(formatPrice(price))}</text>`;
  }).join("");
  const verticalGrid = Array.from({ length: 5 }, (_, index) => {
    const ratio = index / 4;
    const at = timeStart + ratio * (timeEnd - timeStart);
    const xx = left + ratio * plotWidth;
    return `<line x1="${xx}" y1="${top}" x2="${xx}" y2="${bottom}" stroke="${COLORS.grid}" stroke-width="1" opacity="0.5"/><text x="${xx}" y="${bottom + 22}" fill="${COLORS.dim}" font-size="12" text-anchor="middle">${escapeXml(formatTaipeiShort(at))}</text>`;
  }).join("");
  const zoneSvg = zones.map((zone) => {
    const from = Math.min(y(zone.from), y(zone.to));
    const to = Math.max(y(zone.from), y(zone.to));
    return `<rect x="${x(viewportStart)}" y="${from}" width="${Math.max(1, x(viewportEnd) - x(viewportStart))}" height="${Math.max(1, to - from)}" fill="${zone.color}" opacity="0.12"/>`;
  }).join("");
  const levelSvg = levels.map((level) => {
    const yy = y(level.price);
    return `<line x1="${left}" y1="${yy}" x2="${right}" y2="${yy}" stroke="${level.color}" stroke-width="1.5" stroke-dasharray="${level.dash ?? "7 6"}" opacity="0.95"/>`;
  }).join("");
  const candleWidth = Math.max(2, Math.min(14, plotWidth / Math.max(visible.length, 1) * 0.68));
  const candleSvg = visible.map((candle) => {
    const xx = x(candle.openTime + intervalMs / 2);
    const up = candle.close >= candle.open;
    const color = up ? COLORS.up : COLORS.down;
    const openY = y(candle.open);
    const closeY = y(candle.close);
    const bodyY = Math.min(openY, closeY);
    const bodyHeight = Math.max(1, Math.abs(openY - closeY));
    return `<line x1="${xx}" y1="${y(candle.high)}" x2="${xx}" y2="${y(candle.low)}" stroke="${color}" stroke-width="1.2"/><rect x="${xx - candleWidth / 2}" y="${bodyY}" width="${candleWidth}" height="${bodyHeight}" fill="${color}"/>`;
  }).join("");
  const emaSvg = [
    { points: ema20, color: COLORS.ema20, label: "EMA20" },
    { points: ema50, color: COLORS.ema50, label: "EMA50" },
  ].map((line) => {
    const points = linePoints(line.points, x, y, timeStart, timeEnd);
    return points ? `<polyline points="${points}" fill="none" stroke="${line.color}" stroke-width="2"/>` : "";
  }).join("");
  const structureSvg = [resistance, support].filter((line): line is StructuralLine => line !== null).map((line) => {
    const points = linePoints(line.points, x, y, timeStart, timeEnd);
    const color = line.kind === "RESISTANCE" ? COLORS.resistance : COLORS.support;
    return points ? `<polyline points="${points}" fill="none" stroke="${color}" stroke-width="2.2"/>` : "";
  }).join("");
  const markerSvg = markers.map((marker) => {
    if (marker.at < timeStart || marker.at > timeEnd || !positive(marker.price)) return "";
    const xx = x(marker.at);
    const yy = y(marker.price);
    const up = marker.position === "above";
    const down = marker.position === "below";
    const labelY = up ? Math.max(top + 14, yy - 16) : down ? Math.min(bottom - 6, yy + 24) : Math.max(top + 14, yy - 12);
    const triangle = up
      ? `${xx},${yy - 6} ${xx - 5},${yy + 4} ${xx + 5},${yy + 4}`
      : down
        ? `${xx},${yy + 6} ${xx - 5},${yy - 4} ${xx + 5},${yy - 4}`
        : "";
    const shape = marker.position === "middle"
      ? `<circle cx="${xx}" cy="${yy}" r="5" fill="${marker.color}" stroke="#071016" stroke-width="2"/>`
      : `<polygon points="${triangle}" fill="${marker.color}" stroke="#071016" stroke-width="1"/>`;
    const labelAnchor = marker.labelAnchor ?? "start";
    const labelX = xx + (labelAnchor === "end" ? -8 : 8);
    return `${shape}<text x="${labelX}" y="${labelY}" fill="${marker.color}" font-size="12" font-weight="700" text-anchor="${labelAnchor}">${escapeXml(marker.label)}</text>`;
  }).join("");
  const legendRows = [
    ...levels.map((level) => ({ color: level.color, text: `${level.label} ${formatPrice(level.price)}` })),
    { color: COLORS.ema20, text: "EMA20" },
    { color: COLORS.ema50, text: "EMA50" },
    ...(showStructure ? [{ color: COLORS.resistance, text: "Structural resistance" }, { color: COLORS.support, text: "Structural support" }] : []),
  ];
  const legendSvg = legendRows.slice(0, 12).map((item, index) => {
    const column = index % 4;
    const row = Math.floor(index / 4);
    const xx = outerX + 16 + column * 375;
    const yy = outerY + height - 52 + row * 16;
    return `<rect x="${xx}" y="${yy - 9}" width="10" height="3" fill="${item.color}"/><text x="${xx + 15}" y="${yy}" fill="${COLORS.dim}" font-size="11">${escapeXml(item.text)}</text>`;
  }).join("");
  return `<g>
    <rect x="${outerX}" y="${outerY}" width="${width}" height="${height}" rx="8" fill="${COLORS.panel}" stroke="${COLORS.border}"/>
    <text x="${outerX + 16}" y="${outerY + 22}" fill="${COLORS.text}" font-size="16" font-weight="700">${escapeXml(title)}</text>
    <text x="${outerX + 16}" y="${outerY + 39}" fill="${COLORS.dim}" font-size="11">${escapeXml(subtitle)}</text>
    <clipPath id="${clipId}"><rect x="${left}" y="${top}" width="${plotWidth}" height="${plotHeight}"/></clipPath>
    ${horizontalGrid}${verticalGrid}
    <g clip-path="url(#${clipId})">${zoneSvg}${levelSvg}${structureSvg}${candleSvg}${emaSvg}${markerSvg}</g>
    ${legendSvg}
  </g>`;
}

function snapshotAssetFile(tradeId: string): string | null {
  return /^[a-z0-9-]{4,64}$/i.test(tradeId) ? `${tradeId}.svg` : null;
}

function unavailableSnapshot(requestedAt: string, entryAt: string | null, exitAt: string | null, reason: string): DailyRangeClosedChartSnapshot {
  return {
    version: DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION,
    status: "UNAVAILABLE",
    requestedAt,
    capturedAt: null,
    source: "BINANCE_USDM_COMPLETED_CANDLES",
    entryAt,
    exitAt,
    assetFile: null,
    mimeType: null,
    fiveMinuteCandleCount: 0,
    fourHourCandleCount: 0,
    reason,
  };
}

export function pendingDailyRangeClosedChartSnapshot(trade: Pick<DailyRangeClosedChartSnapshotTrade, "entryFilledAt" | "entrySubmittedAt" | "exitTimestamp">, requestedAt: string): DailyRangeClosedChartSnapshot {
  return {
    version: DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION,
    status: "PENDING",
    requestedAt,
    capturedAt: null,
    source: "BINANCE_USDM_COMPLETED_CANDLES",
    entryAt: trade.entryFilledAt ?? trade.entrySubmittedAt ?? null,
    exitAt: trade.exitTimestamp ?? null,
    assetFile: null,
    mimeType: null,
    fiveMinuteCandleCount: 0,
    fourHourCandleCount: 0,
    reason: null,
  };
}

export function renderDailyRangeClosedChartSvg(input: {
  trade: DailyRangeClosedChartSnapshotTrade;
  fiveMinuteCandles: SnapshotCandle[];
  fourHourCandles: SnapshotCandle[];
  entryAtMs: number;
  exitAtMs: number;
}): string {
  const { trade, fiveMinuteCandles, fourHourCandles, entryAtMs, exitAtMs } = input;
  const routeLabel = trade.entryPolicy === "FADE" ? "FADE" : trade.entryPolicy === "CONTINUATION" ? "CONTINUATION" : "LEGACY CONTINUATION";
  const directionText = trade.breakoutDirection ? ` · breakout ${trade.breakoutDirection}` : "";
  const fiveMinuteStart = Math.min(
    entryAtMs,
    trade.confirmationBar1.openTime,
    trade.confirmationBar2.openTime,
  ) - FIVE_MINUTE_MS;
  const fourHourStart = fourHourCandles.length ? fourHourCandles[0]!.openTime : entryAtMs - FOUR_HOURS_MS;
  const referenceStart = finite(trade.referenceRangeOpenTime) ? trade.referenceRangeOpenTime : null;
  const referenceEnd = finite(trade.referenceRangeCloseTime) ? trade.referenceRangeCloseTime : null;
  const sessionText = referenceStart !== null && referenceEnd !== null
    ? `${formatTaipei(referenceStart)}–${formatTaipei(referenceEnd)} ${trade.referenceTimezone === "America/New_York" ? "New York reference" : "UTC reference"}`
    : "persisted 4H reference";
  const breakoutReference = trade.breakoutDirection === "DOWN" || (!trade.breakoutDirection && trade.direction === "SHORT")
    ? { label: "Breakout reference", price: trade.rangeLow, color: COLORS.rangeLow }
    : { label: "Breakout reference", price: trade.rangeHigh, color: COLORS.rangeHigh };
  const contextLevels: PriceLevel[] = [
    { label: "4H range high", price: trade.rangeHigh, color: COLORS.rangeHigh },
    { label: "4H range low", price: trade.rangeLow, color: COLORS.rangeLow },
    { label: "Entry", price: trade.entryFillPrice!, color: COLORS.entry },
    ...(positive(trade.stopPrice) ? [{ label: "Native SL", price: trade.stopPrice, color: COLORS.stop }] : []),
    ...(positive(trade.takeProfitPrice) ? [{ label: "Target / TP", price: trade.takeProfitPrice, color: COLORS.takeProfit }] : []),
    { label: "Exit fill", price: trade.exitPrice!, color: COLORS.exit },
  ];
  // The 5m panel is an execution review, not a 4H range map. Including the
  // opposite range boundary in its price scale can flatten every relevant
  // candle when the 4H range is wide. Keep the full context in the 4H panel
  // and show only the level that actually triggered the trade below.
  const executionLevels: PriceLevel[] = [
    breakoutReference,
    { label: "Entry", price: trade.entryFillPrice!, color: COLORS.entry },
    ...(positive(trade.stopPrice) ? [{ label: "Native SL", price: trade.stopPrice, color: COLORS.stop }] : []),
    ...(positive(trade.takeProfitPrice) ? [{ label: "Target / TP", price: trade.takeProfitPrice, color: COLORS.takeProfit }] : []),
    { label: "Exit fill", price: trade.exitPrice!, color: COLORS.exit },
  ];
  const breakoutPosition = trade.breakoutDirection === "DOWN" ? "below" : "above" as const;
  const c2Position = trade.breakoutDirection === "DOWN" ? "above" : "below" as const;
  const markers: SnapshotMarker[] = [
    {
      label: "C1 breakout",
      at: trade.confirmationBar1.openTime + FIVE_MINUTE_MS,
      price: trade.confirmationBar1.close,
      color: breakoutReference.color,
      position: breakoutPosition,
    },
    {
      label: `C2 ${trade.entryPolicy === "FADE" ? "re-entry" : "continuation"}`,
      at: trade.confirmationBar2.openTime + FIVE_MINUTE_MS,
      price: trade.confirmationBar2.close,
      color: COLORS.rangeLow,
      position: c2Position,
      labelAnchor: "end",
    },
    { label: "ENTRY", at: entryAtMs, price: trade.entryFillPrice!, color: COLORS.entry, position: "middle" },
    { label: "EXIT", at: exitAtMs, price: trade.exitPrice!, color: COLORS.exit, position: "middle", labelAnchor: "end" },
  ];
  const zones: RiskZone[] = [
    ...(positive(trade.stopPrice) ? [{ from: trade.entryFillPrice!, to: trade.stopPrice, color: COLORS.stop, label: "risk to SL" }] : []),
    ...(positive(trade.takeProfitPrice) ? [{ from: trade.entryFillPrice!, to: trade.takeProfitPrice, color: COLORS.takeProfit, label: "target to TP" }] : []),
  ];
  const top = renderPanel({
    x: 32, y: 108, width: 1536, height: 420,
    title: "4H · EMA20/EMA50 + structural support / resistance",
    subtitle: `${trade.symbol} · ${trade.direction} · ${sessionText}`,
    candles: fourHourCandles,
    allCandles: fourHourCandles,
    intervalMs: FOUR_HOURS_MS,
    viewportStart: fourHourStart,
    viewportEnd: exitAtMs,
    levels: contextLevels,
    markers: [
      { label: "ENTRY", at: entryAtMs, price: trade.entryFillPrice!, color: COLORS.entry, position: "middle" },
      { label: "EXIT", at: exitAtMs, price: trade.exitPrice!, color: COLORS.exit, position: "middle", labelAnchor: "end" },
    ],
    showStructure: true,
  });
  const bottom = renderPanel({
    x: 32, y: 562, width: 1536, height: 590,
    title: "5m · final execution path",
    subtitle: `${routeLabel}${directionText} · completed candles only · entry ${formatTaipei(entryAtMs)} → exit ${formatTaipei(exitAtMs)} Taipei`,
    candles: fiveMinuteCandles,
    allCandles: fiveMinuteCandles,
    intervalMs: FIVE_MINUTE_MS,
    viewportStart: fiveMinuteStart,
    viewportEnd: exitAtMs,
    levels: executionLevels,
    markers,
    zones,
  });
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1184" viewBox="0 0 1600 1184" role="img" aria-labelledby="snapshot-title snapshot-desc">
  <title id="snapshot-title">${escapeXml(`${trade.symbol} Daily Range 4H closed chart snapshot`)}</title>
  <desc id="snapshot-desc">Immutable completed-candle chart captured for the confirmed trade close. It starts at the entry context and ends at the exact exit fill.</desc>
  <rect width="1600" height="1184" fill="${COLORS.background}"/>
  <text x="32" y="38" fill="${COLORS.text}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="22" font-weight="700">DAILY RANGE 4H · CLOSED CHART SNAPSHOT</text>
  <text x="32" y="66" fill="${COLORS.dim}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="14">${escapeXml(`${trade.symbol} · ${trade.direction} · ${routeLabel} · entry ${formatPrice(trade.entryFillPrice!)} · exit ${formatPrice(trade.exitPrice!)} · captured at confirmed close`)}</text>
  <text x="32" y="88" fill="${COLORS.dim}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="12">All candles are completed Binance USD-M candles at or before the confirmed exit. This image never refreshes with later price action.</text>
  <g font-family="ui-monospace, SFMono-Regular, Menlo, monospace">${top}${bottom}</g>
</svg>`;
}

export async function captureDailyRangeClosedChartSnapshot(input: {
  directory: string;
  client: DailyRangeClosedChartSnapshotClient;
  trade: DailyRangeClosedChartSnapshotTrade;
  nowMs?: () => number;
}): Promise<DailyRangeClosedChartSnapshot> {
  const requestedAt = new Date(input.nowMs?.() ?? Date.now()).toISOString();
  const entryAtMs = toMs(input.trade.entryFilledAt ?? input.trade.entrySubmittedAt);
  const exitAtMs = toMs(input.trade.exitTimestamp);
  if (entryAtMs === null || exitAtMs === null || exitAtMs < entryAtMs || !positive(input.trade.entryFillPrice) || !positive(input.trade.exitPrice)) {
    return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "ordered confirmed entry and exit fills are required");
  }
  const confirmationBar1 = asSnapshotCandle(input.trade.confirmationBar1);
  const confirmationBar2 = asSnapshotCandle(input.trade.confirmationBar2);
  if (!confirmationBar1 || !confirmationBar2) {
    return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "persisted C1/C2 execution bars are required for a truthful close-time image");
  }
  const assetFile = snapshotAssetFile(input.trade.tradeId);
  if (!assetFile) return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "invalid trade id for snapshot asset");
  const signalStart = Math.min(confirmationBar1.openTime, confirmationBar2.openTime, entryAtMs);
  const fiveMinuteStart = Math.max(0, signalStart - FIVE_MINUTE_EMA_CONTEXT_BARS * FIVE_MINUTE_MS);
  const fiveMinuteEnd = Math.floor((exitAtMs - 1) / FIVE_MINUTE_MS) * FIVE_MINUTE_MS;
  const fourHourEnd = Math.floor((exitAtMs - 1) / FOUR_HOURS_MS) * FOUR_HOURS_MS;
  const fourHourStart = Math.max(0, fourHourEnd - (FOUR_HOUR_CONTEXT_BARS - 1) * FOUR_HOURS_MS);
  try {
    const [fiveMinuteRows, fourHourRows] = await Promise.all([
      input.client.getKlines(input.trade.symbol, "5m", { startTime: fiveMinuteStart, endTime: fiveMinuteEnd }),
      input.client.getKlines(input.trade.symbol, "4h", { startTime: fourHourStart, endTime: fourHourEnd }),
    ]);
    const fiveMinuteCandles = distinctCandles(
      [...fiveMinuteRows, confirmationBar1, confirmationBar2],
      fiveMinuteStart,
      exitAtMs,
    );
    const fourHourCandles = distinctCandles(fourHourRows, fourHourStart, exitAtMs);
    if (fiveMinuteCandles.length === 0) {
      return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "no completed 5m USD-M candle is available before the exit fill");
    }
    if (fourHourCandles.length === 0) {
      return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "no completed 4H USD-M candle is available before the exit fill");
    }
    const svg = renderDailyRangeClosedChartSvg({ trade: input.trade, fiveMinuteCandles, fourHourCandles, entryAtMs, exitAtMs });
    const root = resolve(input.directory);
    mkdirSync(root, { recursive: true });
    const file = resolve(root, assetFile);
    if (!file.startsWith(root + sep)) {
      return unavailableSnapshot(requestedAt, input.trade.entryFilledAt ?? input.trade.entrySubmittedAt ?? null, input.trade.exitTimestamp, "snapshot path escaped its archive directory");
    }
    const temporary = `${file}.tmp-${process.pid}-${Date.now()}`;
    writeFileSync(temporary, svg, "utf8");
    renameSync(temporary, file);
    return {
      version: DAILY_RANGE_CLOSED_CHART_SNAPSHOT_VERSION,
      status: "CAPTURED",
      requestedAt,
      capturedAt: new Date(input.nowMs?.() ?? Date.now()).toISOString(),
      source: "BINANCE_USDM_COMPLETED_CANDLES",
      entryAt: input.trade.entryFilledAt ?? input.trade.entrySubmittedAt,
      exitAt: input.trade.exitTimestamp,
      assetFile,
      mimeType: "image/svg+xml",
      fiveMinuteCandleCount: fiveMinuteCandles.length,
      fourHourCandleCount: fourHourCandles.length,
      reason: null,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      ...pendingDailyRangeClosedChartSnapshot(input.trade, requestedAt),
      reason: `snapshot source unavailable: ${message}`,
    };
  }
}

/** Read only a filename persisted by this module; no user-derived file path is accepted. */
export function readDailyRangeClosedChartSnapshotSvg(
  directory: string,
  snapshot: DailyRangeClosedChartSnapshot | null | undefined,
): string | null {
  if (snapshot?.status !== "CAPTURED" || snapshot.mimeType !== "image/svg+xml" || !snapshot.assetFile) return null;
  const root = resolve(directory);
  if (!/^[a-z0-9-]{4,64}\.svg$/i.test(snapshot.assetFile)) return null;
  const file = resolve(root, snapshot.assetFile);
  if (!file.startsWith(root + sep)) return null;
  try {
    return readFileSync(file, "utf8");
  } catch {
    return null;
  }
}
